/**
 * (C) Copyright IBM Corp. 2026.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * IBM OpenAPI SDK Code Generator Version: 3.113.1-d76630af-20260320-135953
 */

// Package powerhaautomationservicev1 : Operations and models for the PowerhaAutomationServiceV1 service
package powerhaautomationservicev1

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"reflect"
	"time"

	common "github.com/IBM/dra-go-sdk/common"
	"github.com/IBM/go-sdk-core/v5/core"
	"github.com/go-openapi/strfmt"
)

// PowerhaAutomationServiceV1 : No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API Version: 1.0.0
type PowerhaAutomationServiceV1 struct {
	Service *core.BaseService
}

// DefaultServiceURL is the default URL to make service requests to.
const DefaultServiceURL = "https://power-dra.cloud.ibm.com"

// DefaultServiceName is the default key used to find external configuration information.
const DefaultServiceName = "powerha_automation_service"

// PowerhaAutomationServiceV1Options : Service options
type PowerhaAutomationServiceV1Options struct {
	ServiceName   string
	URL           string
	Authenticator core.Authenticator
}

// NewPowerhaAutomationServiceV1UsingExternalConfig : constructs an instance of PowerhaAutomationServiceV1 with passed in options and external configuration.
func NewPowerhaAutomationServiceV1UsingExternalConfig(options *PowerhaAutomationServiceV1Options) (powerhaAutomationService *PowerhaAutomationServiceV1, err error) {
	if options.ServiceName == "" {
		options.ServiceName = DefaultServiceName
	}

	if options.Authenticator == nil {
		options.Authenticator, err = core.GetAuthenticatorFromEnvironment(options.ServiceName)
		if err != nil {
			err = core.SDKErrorf(err, "", "env-auth-error", common.GetComponentInfo())
			return
		}
	}

	powerhaAutomationService, err = NewPowerhaAutomationServiceV1(options)
	err = core.RepurposeSDKProblem(err, "new-client-error")
	if err != nil {
		return
	}

	err = powerhaAutomationService.Service.ConfigureService(options.ServiceName)
	if err != nil {
		err = core.SDKErrorf(err, "", "client-config-error", common.GetComponentInfo())
		return
	}

	if options.URL != "" {
		err = powerhaAutomationService.Service.SetServiceURL(options.URL)
		err = core.RepurposeSDKProblem(err, "url-set-error")
	}
	return
}

// NewPowerhaAutomationServiceV1 : constructs an instance of PowerhaAutomationServiceV1 with passed in options.
func NewPowerhaAutomationServiceV1(options *PowerhaAutomationServiceV1Options) (service *PowerhaAutomationServiceV1, err error) {
	serviceOptions := &core.ServiceOptions{
		URL:           DefaultServiceURL,
		Authenticator: options.Authenticator,
	}

	baseService, err := core.NewBaseService(serviceOptions)
	if err != nil {
		err = core.SDKErrorf(err, "", "new-base-error", common.GetComponentInfo())
		return
	}

	if options.URL != "" {
		err = baseService.SetServiceURL(options.URL)
		if err != nil {
			err = core.SDKErrorf(err, "", "set-url-error", common.GetComponentInfo())
			return
		}
	}

	service = &PowerhaAutomationServiceV1{
		Service: baseService,
	}

	return
}

// GetServiceURLForRegion returns the service URL to be used for the specified region
func GetServiceURLForRegion(region string) (string, error) {
	return "", core.SDKErrorf(nil, "service does not support regional URLs", "no-regional-support", common.GetComponentInfo())
}

// Clone makes a copy of "powerhaAutomationService" suitable for processing requests.
func (powerhaAutomationService *PowerhaAutomationServiceV1) Clone() *PowerhaAutomationServiceV1 {
	if core.IsNil(powerhaAutomationService) {
		return nil
	}
	clone := *powerhaAutomationService
	clone.Service = powerhaAutomationService.Service.Clone()
	return &clone
}

// SetServiceURL sets the service URL
func (powerhaAutomationService *PowerhaAutomationServiceV1) SetServiceURL(url string) error {
	err := powerhaAutomationService.Service.SetServiceURL(url)
	if err != nil {
		err = core.SDKErrorf(err, "", "url-set-error", common.GetComponentInfo())
	}
	return err
}

// GetServiceURL returns the service URL
func (powerhaAutomationService *PowerhaAutomationServiceV1) GetServiceURL() string {
	return powerhaAutomationService.Service.GetServiceURL()
}

// SetDefaultHeaders sets HTTP headers to be sent in every request
func (powerhaAutomationService *PowerhaAutomationServiceV1) SetDefaultHeaders(headers http.Header) {
	powerhaAutomationService.Service.SetDefaultHeaders(headers)
}

// SetEnableGzipCompression sets the service's EnableGzipCompression field
func (powerhaAutomationService *PowerhaAutomationServiceV1) SetEnableGzipCompression(enableGzip bool) {
	powerhaAutomationService.Service.SetEnableGzipCompression(enableGzip)
}

// GetEnableGzipCompression returns the service's EnableGzipCompression field
func (powerhaAutomationService *PowerhaAutomationServiceV1) GetEnableGzipCompression() bool {
	return powerhaAutomationService.Service.GetEnableGzipCompression()
}

// EnableRetries enables automatic retries for requests invoked for this service instance.
// If either parameter is specified as 0, then a default value is used instead.
func (powerhaAutomationService *PowerhaAutomationServiceV1) EnableRetries(maxRetries int, maxRetryInterval time.Duration) {
	powerhaAutomationService.Service.EnableRetries(maxRetries, maxRetryInterval)
}

// DisableRetries disables automatic retries for requests invoked for this service instance.
func (powerhaAutomationService *PowerhaAutomationServiceV1) DisableRetries() {
	powerhaAutomationService.Service.DisableRetries()
}

// GetAPIKey : Get the apikey for the specified PowerHA service instance
// Retrieves existing API key for the specified PowerHA service instance.
func (powerhaAutomationService *PowerhaAutomationServiceV1) GetAPIKey(getAPIKeyOptions *GetAPIKeyOptions) (result *APIKeyResponse, response *core.DetailedResponse, err error) {
	result, response, err = powerhaAutomationService.GetAPIKeyWithContext(context.Background(), getAPIKeyOptions)
	err = core.RepurposeSDKProblem(err, "")
	return
}

// GetAPIKeyWithContext is an alternate form of the GetAPIKey method which supports a Context parameter
func (powerhaAutomationService *PowerhaAutomationServiceV1) GetAPIKeyWithContext(ctx context.Context, getAPIKeyOptions *GetAPIKeyOptions) (result *APIKeyResponse, response *core.DetailedResponse, err error) {
	err = core.ValidateNotNil(getAPIKeyOptions, "getAPIKeyOptions cannot be nil")
	if err != nil {
		err = core.SDKErrorf(err, "", "unexpected-nil-param", common.GetComponentInfo())
		return
	}
	err = core.ValidateStruct(getAPIKeyOptions, "getAPIKeyOptions")
	if err != nil {
		err = core.SDKErrorf(err, "", "struct-validation-error", common.GetComponentInfo())
		return
	}

	pathParamsMap := map[string]string{
		"pha_instance_id": *getAPIKeyOptions.PhaInstanceID,
	}

	builder := core.NewRequestBuilder(core.GET)
	builder = builder.WithContext(ctx)
	builder.EnableGzipCompression = powerhaAutomationService.GetEnableGzipCompression()
	_, err = builder.ResolveRequestURL(powerhaAutomationService.Service.Options.URL, `/powerha_automation/v1/api_key/{pha_instance_id}`, pathParamsMap)
	if err != nil {
		err = core.SDKErrorf(err, "", "url-resolve-error", common.GetComponentInfo())
		return
	}

	sdkHeaders := common.GetSdkHeaders("powerha_automation_service", "V1", "GetAPIKey")
	for headerName, headerValue := range sdkHeaders {
		builder.AddHeader(headerName, headerValue)
	}

	for headerName, headerValue := range getAPIKeyOptions.Headers {
		builder.AddHeader(headerName, headerValue)
	}
	builder.AddHeader("Accept", "application/json")
	if getAPIKeyOptions.AcceptLanguage != nil {
		builder.AddHeader("Accept-Language", fmt.Sprint(*getAPIKeyOptions.AcceptLanguage))
	}
	if getAPIKeyOptions.IfNoneMatch != nil {
		builder.AddHeader("If-None-Match", fmt.Sprint(*getAPIKeyOptions.IfNoneMatch))
	}

	request, err := builder.Build()
	if err != nil {
		err = core.SDKErrorf(err, "", "build-error", common.GetComponentInfo())
		return
	}

	var rawResponse map[string]json.RawMessage
	response, err = powerhaAutomationService.Service.Request(request, &rawResponse)
	if err != nil {
		core.EnrichHTTPProblem(err, "get_api_key", getServiceComponentInfo())
		err = core.SDKErrorf(err, "", "http-request-err", common.GetComponentInfo())
		return
	}
	if rawResponse != nil {
		err = core.UnmarshalModel(rawResponse, "", &result, UnmarshalAPIKeyResponse)
		if err != nil {
			err = core.SDKErrorf(err, "", "unmarshal-resp-error", common.GetComponentInfo())
			return
		}
		response.Result = result
	}

	return
}

// CreateAPIKey : Update the apikey for the specified PowerHA service instance
// Updates a new apikey for the specified PowerHA service instance.
func (powerhaAutomationService *PowerhaAutomationServiceV1) CreateAPIKey(createAPIKeyOptions *CreateAPIKeyOptions) (result *APIKeyResponse, response *core.DetailedResponse, err error) {
	result, response, err = powerhaAutomationService.CreateAPIKeyWithContext(context.Background(), createAPIKeyOptions)
	err = core.RepurposeSDKProblem(err, "")
	return
}

// CreateAPIKeyWithContext is an alternate form of the CreateAPIKey method which supports a Context parameter
func (powerhaAutomationService *PowerhaAutomationServiceV1) CreateAPIKeyWithContext(ctx context.Context, createAPIKeyOptions *CreateAPIKeyOptions) (result *APIKeyResponse, response *core.DetailedResponse, err error) {
	err = core.ValidateNotNil(createAPIKeyOptions, "createAPIKeyOptions cannot be nil")
	if err != nil {
		err = core.SDKErrorf(err, "", "unexpected-nil-param", common.GetComponentInfo())
		return
	}
	err = core.ValidateStruct(createAPIKeyOptions, "createAPIKeyOptions")
	if err != nil {
		err = core.SDKErrorf(err, "", "struct-validation-error", common.GetComponentInfo())
		return
	}

	pathParamsMap := map[string]string{
		"pha_instance_id": *createAPIKeyOptions.PhaInstanceID,
	}

	builder := core.NewRequestBuilder(core.POST)
	builder = builder.WithContext(ctx)
	builder.EnableGzipCompression = powerhaAutomationService.GetEnableGzipCompression()
	_, err = builder.ResolveRequestURL(powerhaAutomationService.Service.Options.URL, `/powerha_automation/v1/api_key/{pha_instance_id}`, pathParamsMap)
	if err != nil {
		err = core.SDKErrorf(err, "", "url-resolve-error", common.GetComponentInfo())
		return
	}

	sdkHeaders := common.GetSdkHeaders("powerha_automation_service", "V1", "CreateAPIKey")
	for headerName, headerValue := range sdkHeaders {
		builder.AddHeader(headerName, headerValue)
	}

	for headerName, headerValue := range createAPIKeyOptions.Headers {
		builder.AddHeader(headerName, headerValue)
	}
	builder.AddHeader("Accept", "application/json")
	builder.AddHeader("Content-Type", "application/json")
	if createAPIKeyOptions.AcceptLanguage != nil {
		builder.AddHeader("Accept-Language", fmt.Sprint(*createAPIKeyOptions.AcceptLanguage))
	}

	body := make(map[string]interface{})
	if createAPIKeyOptions.APIKey != nil {
		body["api_key"] = createAPIKeyOptions.APIKey
	}
	_, err = builder.SetBodyContentJSON(body)
	if err != nil {
		err = core.SDKErrorf(err, "", "set-json-body-error", common.GetComponentInfo())
		return
	}

	request, err := builder.Build()
	if err != nil {
		err = core.SDKErrorf(err, "", "build-error", common.GetComponentInfo())
		return
	}

	var rawResponse map[string]json.RawMessage
	response, err = powerhaAutomationService.Service.Request(request, &rawResponse)
	if err != nil {
		core.EnrichHTTPProblem(err, "create_api_key", getServiceComponentInfo())
		err = core.SDKErrorf(err, "", "http-request-err", common.GetComponentInfo())
		return
	}
	if rawResponse != nil {
		err = core.UnmarshalModel(rawResponse, "", &result, UnmarshalAPIKeyResponse)
		if err != nil {
			err = core.SDKErrorf(err, "", "unmarshal-resp-error", common.GetComponentInfo())
			return
		}
		response.Result = result
	}

	return
}

// GetClusterNode : Retrieves the cluster node details for the specified PowerHA instance
// Retrieves details of all cluster nodes configured for the given PowerHA service instance.
func (powerhaAutomationService *PowerhaAutomationServiceV1) GetClusterNode(getClusterNodeOptions *GetClusterNodeOptions) (result *ClusterNodeResponse, response *core.DetailedResponse, err error) {
	result, response, err = powerhaAutomationService.GetClusterNodeWithContext(context.Background(), getClusterNodeOptions)
	err = core.RepurposeSDKProblem(err, "")
	return
}

// GetClusterNodeWithContext is an alternate form of the GetClusterNode method which supports a Context parameter
func (powerhaAutomationService *PowerhaAutomationServiceV1) GetClusterNodeWithContext(ctx context.Context, getClusterNodeOptions *GetClusterNodeOptions) (result *ClusterNodeResponse, response *core.DetailedResponse, err error) {
	err = core.ValidateNotNil(getClusterNodeOptions, "getClusterNodeOptions cannot be nil")
	if err != nil {
		err = core.SDKErrorf(err, "", "unexpected-nil-param", common.GetComponentInfo())
		return
	}
	err = core.ValidateStruct(getClusterNodeOptions, "getClusterNodeOptions")
	if err != nil {
		err = core.SDKErrorf(err, "", "struct-validation-error", common.GetComponentInfo())
		return
	}

	pathParamsMap := map[string]string{
		"pha_instance_id": *getClusterNodeOptions.PhaInstanceID,
	}

	builder := core.NewRequestBuilder(core.GET)
	builder = builder.WithContext(ctx)
	builder.EnableGzipCompression = powerhaAutomationService.GetEnableGzipCompression()
	_, err = builder.ResolveRequestURL(powerhaAutomationService.Service.Options.URL, `/powerha_automation/v1/cluster_nodes/{pha_instance_id}`, pathParamsMap)
	if err != nil {
		err = core.SDKErrorf(err, "", "url-resolve-error", common.GetComponentInfo())
		return
	}

	sdkHeaders := common.GetSdkHeaders("powerha_automation_service", "V1", "GetClusterNode")
	for headerName, headerValue := range sdkHeaders {
		builder.AddHeader(headerName, headerValue)
	}

	for headerName, headerValue := range getClusterNodeOptions.Headers {
		builder.AddHeader(headerName, headerValue)
	}
	builder.AddHeader("Accept", "application/json")
	if getClusterNodeOptions.IfNoneMatch != nil {
		builder.AddHeader("If-None-Match", fmt.Sprint(*getClusterNodeOptions.IfNoneMatch))
	}

	request, err := builder.Build()
	if err != nil {
		err = core.SDKErrorf(err, "", "build-error", common.GetComponentInfo())
		return
	}

	var rawResponse map[string]json.RawMessage
	response, err = powerhaAutomationService.Service.Request(request, &rawResponse)
	if err != nil {
		core.EnrichHTTPProblem(err, "get_cluster_node", getServiceComponentInfo())
		err = core.SDKErrorf(err, "", "http-request-err", common.GetComponentInfo())
		return
	}
	if rawResponse != nil {
		err = core.UnmarshalModel(rawResponse, "", &result, UnmarshalClusterNodeResponse)
		if err != nil {
			err = core.SDKErrorf(err, "", "unmarshal-resp-error", common.GetComponentInfo())
			return
		}
		response.Result = result
	}

	return
}

// CreateClusterNode : Add a new cluster node
// Adds a new node to the PowerHA cluster for the specified PowerHA service instance.
func (powerhaAutomationService *PowerhaAutomationServiceV1) CreateClusterNode(createClusterNodeOptions *CreateClusterNodeOptions) (result *ClusterNodeResponse, response *core.DetailedResponse, err error) {
	result, response, err = powerhaAutomationService.CreateClusterNodeWithContext(context.Background(), createClusterNodeOptions)
	err = core.RepurposeSDKProblem(err, "")
	return
}

// CreateClusterNodeWithContext is an alternate form of the CreateClusterNode method which supports a Context parameter
func (powerhaAutomationService *PowerhaAutomationServiceV1) CreateClusterNodeWithContext(ctx context.Context, createClusterNodeOptions *CreateClusterNodeOptions) (result *ClusterNodeResponse, response *core.DetailedResponse, err error) {
	err = core.ValidateNotNil(createClusterNodeOptions, "createClusterNodeOptions cannot be nil")
	if err != nil {
		err = core.SDKErrorf(err, "", "unexpected-nil-param", common.GetComponentInfo())
		return
	}
	err = core.ValidateStruct(createClusterNodeOptions, "createClusterNodeOptions")
	if err != nil {
		err = core.SDKErrorf(err, "", "struct-validation-error", common.GetComponentInfo())
		return
	}

	pathParamsMap := map[string]string{
		"pha_instance_id": *createClusterNodeOptions.PhaInstanceID,
	}

	builder := core.NewRequestBuilder(core.POST)
	builder = builder.WithContext(ctx)
	builder.EnableGzipCompression = powerhaAutomationService.GetEnableGzipCompression()
	_, err = builder.ResolveRequestURL(powerhaAutomationService.Service.Options.URL, `/powerha_automation/v1/cluster_nodes/{pha_instance_id}`, pathParamsMap)
	if err != nil {
		err = core.SDKErrorf(err, "", "url-resolve-error", common.GetComponentInfo())
		return
	}

	sdkHeaders := common.GetSdkHeaders("powerha_automation_service", "V1", "CreateClusterNode")
	for headerName, headerValue := range sdkHeaders {
		builder.AddHeader(headerName, headerValue)
	}

	for headerName, headerValue := range createClusterNodeOptions.Headers {
		builder.AddHeader(headerName, headerValue)
	}
	builder.AddHeader("Accept", "application/json")
	builder.AddHeader("Content-Type", "application/json")
	if createClusterNodeOptions.AcceptLanguage != nil {
		builder.AddHeader("Accept-Language", fmt.Sprint(*createClusterNodeOptions.AcceptLanguage))
	}
	if createClusterNodeOptions.IfNoneMatch != nil {
		builder.AddHeader("If-None-Match", fmt.Sprint(*createClusterNodeOptions.IfNoneMatch))
	}

	body := make(map[string]interface{})
	if createClusterNodeOptions.PrimaryClusterNodes != nil {
		body["primary_cluster_nodes"] = createClusterNodeOptions.PrimaryClusterNodes
	}
	if createClusterNodeOptions.SecondaryClusterNodes != nil {
		body["secondary_cluster_nodes"] = createClusterNodeOptions.SecondaryClusterNodes
	}
	_, err = builder.SetBodyContentJSON(body)
	if err != nil {
		err = core.SDKErrorf(err, "", "set-json-body-error", common.GetComponentInfo())
		return
	}

	request, err := builder.Build()
	if err != nil {
		err = core.SDKErrorf(err, "", "build-error", common.GetComponentInfo())
		return
	}

	var rawResponse map[string]json.RawMessage
	response, err = powerhaAutomationService.Service.Request(request, &rawResponse)
	if err != nil {
		core.EnrichHTTPProblem(err, "create_cluster_node", getServiceComponentInfo())
		err = core.SDKErrorf(err, "", "http-request-err", common.GetComponentInfo())
		return
	}
	if rawResponse != nil {
		err = core.UnmarshalModel(rawResponse, "", &result, UnmarshalClusterNodeResponse)
		if err != nil {
			err = core.SDKErrorf(err, "", "unmarshal-resp-error", common.GetComponentInfo())
			return
		}
		response.Result = result
	}

	return
}

// DeleteClusterNode : Delete a cluster node
// Removes the specified cluster node from the PowerHA service instance.
func (powerhaAutomationService *PowerhaAutomationServiceV1) DeleteClusterNode(deleteClusterNodeOptions *DeleteClusterNodeOptions) (result *ClusterNodeResponse, response *core.DetailedResponse, err error) {
	result, response, err = powerhaAutomationService.DeleteClusterNodeWithContext(context.Background(), deleteClusterNodeOptions)
	err = core.RepurposeSDKProblem(err, "")
	return
}

// DeleteClusterNodeWithContext is an alternate form of the DeleteClusterNode method which supports a Context parameter
func (powerhaAutomationService *PowerhaAutomationServiceV1) DeleteClusterNodeWithContext(ctx context.Context, deleteClusterNodeOptions *DeleteClusterNodeOptions) (result *ClusterNodeResponse, response *core.DetailedResponse, err error) {
	err = core.ValidateNotNil(deleteClusterNodeOptions, "deleteClusterNodeOptions cannot be nil")
	if err != nil {
		err = core.SDKErrorf(err, "", "unexpected-nil-param", common.GetComponentInfo())
		return
	}
	err = core.ValidateStruct(deleteClusterNodeOptions, "deleteClusterNodeOptions")
	if err != nil {
		err = core.SDKErrorf(err, "", "struct-validation-error", common.GetComponentInfo())
		return
	}

	pathParamsMap := map[string]string{
		"pha_instance_id": *deleteClusterNodeOptions.PhaInstanceID,
	}

	builder := core.NewRequestBuilder(core.DELETE)
	builder = builder.WithContext(ctx)
	builder.EnableGzipCompression = powerhaAutomationService.GetEnableGzipCompression()
	_, err = builder.ResolveRequestURL(powerhaAutomationService.Service.Options.URL, `/powerha_automation/v1/cluster_nodes/{pha_instance_id}`, pathParamsMap)
	if err != nil {
		err = core.SDKErrorf(err, "", "url-resolve-error", common.GetComponentInfo())
		return
	}

	sdkHeaders := common.GetSdkHeaders("powerha_automation_service", "V1", "DeleteClusterNode")
	for headerName, headerValue := range sdkHeaders {
		builder.AddHeader(headerName, headerValue)
	}

	for headerName, headerValue := range deleteClusterNodeOptions.Headers {
		builder.AddHeader(headerName, headerValue)
	}
	builder.AddHeader("Accept", "application/json")
	if deleteClusterNodeOptions.IfNoneMatch != nil {
		builder.AddHeader("If-None-Match", fmt.Sprint(*deleteClusterNodeOptions.IfNoneMatch))
	}

	builder.AddQuery("vm_id", fmt.Sprint(*deleteClusterNodeOptions.VMID))

	request, err := builder.Build()
	if err != nil {
		err = core.SDKErrorf(err, "", "build-error", common.GetComponentInfo())
		return
	}

	var rawResponse map[string]json.RawMessage
	response, err = powerhaAutomationService.Service.Request(request, &rawResponse)
	if err != nil {
		core.EnrichHTTPProblem(err, "delete_cluster_node", getServiceComponentInfo())
		err = core.SDKErrorf(err, "", "http-request-err", common.GetComponentInfo())
		return
	}
	if rawResponse != nil {
		err = core.UnmarshalModel(rawResponse, "", &result, UnmarshalClusterNodeResponse)
		if err != nil {
			err = core.SDKErrorf(err, "", "unmarshal-resp-error", common.GetComponentInfo())
			return
		}
		response.Result = result
	}

	return
}

// GetPowervsWorkspace : List of PowerVS workspaces based on location
// Retrieves list of powerVS workspaces related to the PowerHA service instance based on location.
func (powerhaAutomationService *PowerhaAutomationServiceV1) GetPowervsWorkspace(getPowervsWorkspaceOptions *GetPowervsWorkspaceOptions) (result *PhaWorkspacesRegionResponse, response *core.DetailedResponse, err error) {
	result, response, err = powerhaAutomationService.GetPowervsWorkspaceWithContext(context.Background(), getPowervsWorkspaceOptions)
	err = core.RepurposeSDKProblem(err, "")
	return
}

// GetPowervsWorkspaceWithContext is an alternate form of the GetPowervsWorkspace method which supports a Context parameter
func (powerhaAutomationService *PowerhaAutomationServiceV1) GetPowervsWorkspaceWithContext(ctx context.Context, getPowervsWorkspaceOptions *GetPowervsWorkspaceOptions) (result *PhaWorkspacesRegionResponse, response *core.DetailedResponse, err error) {
	err = core.ValidateNotNil(getPowervsWorkspaceOptions, "getPowervsWorkspaceOptions cannot be nil")
	if err != nil {
		err = core.SDKErrorf(err, "", "unexpected-nil-param", common.GetComponentInfo())
		return
	}
	err = core.ValidateStruct(getPowervsWorkspaceOptions, "getPowervsWorkspaceOptions")
	if err != nil {
		err = core.SDKErrorf(err, "", "struct-validation-error", common.GetComponentInfo())
		return
	}

	pathParamsMap := map[string]string{
		"pha_instance_id": *getPowervsWorkspaceOptions.PhaInstanceID,
	}

	builder := core.NewRequestBuilder(core.GET)
	builder = builder.WithContext(ctx)
	builder.EnableGzipCompression = powerhaAutomationService.GetEnableGzipCompression()
	_, err = builder.ResolveRequestURL(powerhaAutomationService.Service.Options.URL, `/powerha_automation/v1/powervs_workspaces/{pha_instance_id}`, pathParamsMap)
	if err != nil {
		err = core.SDKErrorf(err, "", "url-resolve-error", common.GetComponentInfo())
		return
	}

	sdkHeaders := common.GetSdkHeaders("powerha_automation_service", "V1", "GetPowervsWorkspace")
	for headerName, headerValue := range sdkHeaders {
		builder.AddHeader(headerName, headerValue)
	}

	for headerName, headerValue := range getPowervsWorkspaceOptions.Headers {
		builder.AddHeader(headerName, headerValue)
	}
	builder.AddHeader("Accept", "application/json")
	if getPowervsWorkspaceOptions.AcceptLanguage != nil {
		builder.AddHeader("Accept-Language", fmt.Sprint(*getPowervsWorkspaceOptions.AcceptLanguage))
	}
	if getPowervsWorkspaceOptions.IfNoneMatch != nil {
		builder.AddHeader("If-None-Match", fmt.Sprint(*getPowervsWorkspaceOptions.IfNoneMatch))
	}

	builder.AddQuery("location_id", fmt.Sprint(*getPowervsWorkspaceOptions.LocationID))

	request, err := builder.Build()
	if err != nil {
		err = core.SDKErrorf(err, "", "build-error", common.GetComponentInfo())
		return
	}

	var rawResponse map[string]json.RawMessage
	response, err = powerhaAutomationService.Service.Request(request, &rawResponse)
	if err != nil {
		core.EnrichHTTPProblem(err, "get_powervs_workspace", getServiceComponentInfo())
		err = core.SDKErrorf(err, "", "http-request-err", common.GetComponentInfo())
		return
	}
	if rawResponse != nil {
		err = core.UnmarshalModel(rawResponse, "", &result, UnmarshalPhaWorkspacesRegionResponse)
		if err != nil {
			err = core.SDKErrorf(err, "", "unmarshal-resp-error", common.GetComponentInfo())
			return
		}
		response.Result = result
	}

	return
}

// GetPhaLastOperation : View details of the last operation performed on the PowerHA instance
// Retrieves the most recent operation performed on the PowerHA service instance.
func (powerhaAutomationService *PowerhaAutomationServiceV1) GetPhaLastOperation(getPhaLastOperationOptions *GetPhaLastOperationOptions) (result *ServiceInstancePhaStatus, response *core.DetailedResponse, err error) {
	result, response, err = powerhaAutomationService.GetPhaLastOperationWithContext(context.Background(), getPhaLastOperationOptions)
	err = core.RepurposeSDKProblem(err, "")
	return
}

// GetPhaLastOperationWithContext is an alternate form of the GetPhaLastOperation method which supports a Context parameter
func (powerhaAutomationService *PowerhaAutomationServiceV1) GetPhaLastOperationWithContext(ctx context.Context, getPhaLastOperationOptions *GetPhaLastOperationOptions) (result *ServiceInstancePhaStatus, response *core.DetailedResponse, err error) {
	err = core.ValidateNotNil(getPhaLastOperationOptions, "getPhaLastOperationOptions cannot be nil")
	if err != nil {
		err = core.SDKErrorf(err, "", "unexpected-nil-param", common.GetComponentInfo())
		return
	}
	err = core.ValidateStruct(getPhaLastOperationOptions, "getPhaLastOperationOptions")
	if err != nil {
		err = core.SDKErrorf(err, "", "struct-validation-error", common.GetComponentInfo())
		return
	}

	pathParamsMap := map[string]string{
		"pha_instance_id": *getPhaLastOperationOptions.PhaInstanceID,
	}

	builder := core.NewRequestBuilder(core.GET)
	builder = builder.WithContext(ctx)
	builder.EnableGzipCompression = powerhaAutomationService.GetEnableGzipCompression()
	_, err = builder.ResolveRequestURL(powerhaAutomationService.Service.Options.URL, `/powerha_automation/v1/last_operation/{pha_instance_id}`, pathParamsMap)
	if err != nil {
		err = core.SDKErrorf(err, "", "url-resolve-error", common.GetComponentInfo())
		return
	}

	sdkHeaders := common.GetSdkHeaders("powerha_automation_service", "V1", "GetPhaLastOperation")
	for headerName, headerValue := range sdkHeaders {
		builder.AddHeader(headerName, headerValue)
	}

	for headerName, headerValue := range getPhaLastOperationOptions.Headers {
		builder.AddHeader(headerName, headerValue)
	}
	builder.AddHeader("Accept", "application/json")
	if getPhaLastOperationOptions.AcceptLanguage != nil {
		builder.AddHeader("Accept-Language", fmt.Sprint(*getPhaLastOperationOptions.AcceptLanguage))
	}
	if getPhaLastOperationOptions.IfNoneMatch != nil {
		builder.AddHeader("If-None-Match", fmt.Sprint(*getPhaLastOperationOptions.IfNoneMatch))
	}

	request, err := builder.Build()
	if err != nil {
		err = core.SDKErrorf(err, "", "build-error", common.GetComponentInfo())
		return
	}

	var rawResponse map[string]json.RawMessage
	response, err = powerhaAutomationService.Service.Request(request, &rawResponse)
	if err != nil {
		core.EnrichHTTPProblem(err, "get_pha_last_operation", getServiceComponentInfo())
		err = core.SDKErrorf(err, "", "http-request-err", common.GetComponentInfo())
		return
	}
	if rawResponse != nil {
		err = core.UnmarshalModel(rawResponse, "", &result, UnmarshalServiceInstancePhaStatus)
		if err != nil {
			err = core.SDKErrorf(err, "", "unmarshal-resp-error", common.GetComponentInfo())
			return
		}
		response.Result = result
	}

	return
}

// GetPhaDeployment : Retrieves deployment details
// Retrieves the PowerHA deployment configuration, status, and associated metadata.
func (powerhaAutomationService *PowerhaAutomationServiceV1) GetPhaDeployment(getPhaDeploymentOptions *GetPhaDeploymentOptions) (result *PhaDeploymentResponse, response *core.DetailedResponse, err error) {
	result, response, err = powerhaAutomationService.GetPhaDeploymentWithContext(context.Background(), getPhaDeploymentOptions)
	err = core.RepurposeSDKProblem(err, "")
	return
}

// GetPhaDeploymentWithContext is an alternate form of the GetPhaDeployment method which supports a Context parameter
func (powerhaAutomationService *PowerhaAutomationServiceV1) GetPhaDeploymentWithContext(ctx context.Context, getPhaDeploymentOptions *GetPhaDeploymentOptions) (result *PhaDeploymentResponse, response *core.DetailedResponse, err error) {
	err = core.ValidateNotNil(getPhaDeploymentOptions, "getPhaDeploymentOptions cannot be nil")
	if err != nil {
		err = core.SDKErrorf(err, "", "unexpected-nil-param", common.GetComponentInfo())
		return
	}
	err = core.ValidateStruct(getPhaDeploymentOptions, "getPhaDeploymentOptions")
	if err != nil {
		err = core.SDKErrorf(err, "", "struct-validation-error", common.GetComponentInfo())
		return
	}

	pathParamsMap := map[string]string{
		"pha_instance_id": *getPhaDeploymentOptions.PhaInstanceID,
	}

	builder := core.NewRequestBuilder(core.GET)
	builder = builder.WithContext(ctx)
	builder.EnableGzipCompression = powerhaAutomationService.GetEnableGzipCompression()
	_, err = builder.ResolveRequestURL(powerhaAutomationService.Service.Options.URL, `/powerha_automation/v1/pha_deployment/{pha_instance_id}`, pathParamsMap)
	if err != nil {
		err = core.SDKErrorf(err, "", "url-resolve-error", common.GetComponentInfo())
		return
	}

	sdkHeaders := common.GetSdkHeaders("powerha_automation_service", "V1", "GetPhaDeployment")
	for headerName, headerValue := range sdkHeaders {
		builder.AddHeader(headerName, headerValue)
	}

	for headerName, headerValue := range getPhaDeploymentOptions.Headers {
		builder.AddHeader(headerName, headerValue)
	}
	builder.AddHeader("Accept", "application/json")
	if getPhaDeploymentOptions.IfNoneMatch != nil {
		builder.AddHeader("If-None-Match", fmt.Sprint(*getPhaDeploymentOptions.IfNoneMatch))
	}

	request, err := builder.Build()
	if err != nil {
		err = core.SDKErrorf(err, "", "build-error", common.GetComponentInfo())
		return
	}

	var rawResponse map[string]json.RawMessage
	response, err = powerhaAutomationService.Service.Request(request, &rawResponse)
	if err != nil {
		core.EnrichHTTPProblem(err, "get_pha_deployment", getServiceComponentInfo())
		err = core.SDKErrorf(err, "", "http-request-err", common.GetComponentInfo())
		return
	}
	if rawResponse != nil {
		err = core.UnmarshalModel(rawResponse, "", &result, UnmarshalPhaDeploymentResponse)
		if err != nil {
			err = core.SDKErrorf(err, "", "unmarshal-resp-error", common.GetComponentInfo())
			return
		}
		response.Result = result
	}

	return
}

// CreatePhaDeployment : Create a new deployment
// Create a new PowerHA deployment for a given location and PowerVS workspace. Refer deploying the PowerHA on Powervs
// https://cloud.ibm.com/docs/dr-automation-powervs?topic=dr-automation-powervs-getting-started-with-ha-automation-for-power-virtual-server
// for more details.
func (powerhaAutomationService *PowerhaAutomationServiceV1) CreatePhaDeployment(createPhaDeploymentOptions *CreatePhaDeploymentOptions) (result *PhaDeploymentResponse, response *core.DetailedResponse, err error) {
	result, response, err = powerhaAutomationService.CreatePhaDeploymentWithContext(context.Background(), createPhaDeploymentOptions)
	err = core.RepurposeSDKProblem(err, "")
	return
}

// CreatePhaDeploymentWithContext is an alternate form of the CreatePhaDeployment method which supports a Context parameter
func (powerhaAutomationService *PowerhaAutomationServiceV1) CreatePhaDeploymentWithContext(ctx context.Context, createPhaDeploymentOptions *CreatePhaDeploymentOptions) (result *PhaDeploymentResponse, response *core.DetailedResponse, err error) {
	err = core.ValidateNotNil(createPhaDeploymentOptions, "createPhaDeploymentOptions cannot be nil")
	if err != nil {
		err = core.SDKErrorf(err, "", "unexpected-nil-param", common.GetComponentInfo())
		return
	}
	err = core.ValidateStruct(createPhaDeploymentOptions, "createPhaDeploymentOptions")
	if err != nil {
		err = core.SDKErrorf(err, "", "struct-validation-error", common.GetComponentInfo())
		return
	}

	pathParamsMap := map[string]string{
		"pha_instance_id": *createPhaDeploymentOptions.PhaInstanceID,
	}

	builder := core.NewRequestBuilder(core.POST)
	builder = builder.WithContext(ctx)
	builder.EnableGzipCompression = powerhaAutomationService.GetEnableGzipCompression()
	_, err = builder.ResolveRequestURL(powerhaAutomationService.Service.Options.URL, `/powerha_automation/v1/pha_deployment/{pha_instance_id}`, pathParamsMap)
	if err != nil {
		err = core.SDKErrorf(err, "", "url-resolve-error", common.GetComponentInfo())
		return
	}

	sdkHeaders := common.GetSdkHeaders("powerha_automation_service", "V1", "CreatePhaDeployment")
	for headerName, headerValue := range sdkHeaders {
		builder.AddHeader(headerName, headerValue)
	}

	for headerName, headerValue := range createPhaDeploymentOptions.Headers {
		builder.AddHeader(headerName, headerValue)
	}
	builder.AddHeader("Accept", "application/json")
	builder.AddHeader("Content-Type", "application/json")
	if createPhaDeploymentOptions.AcceptLanguage != nil {
		builder.AddHeader("Accept-Language", fmt.Sprint(*createPhaDeploymentOptions.AcceptLanguage))
	}
	if createPhaDeploymentOptions.IfNoneMatch != nil {
		builder.AddHeader("If-None-Match", fmt.Sprint(*createPhaDeploymentOptions.IfNoneMatch))
	}

	body := make(map[string]interface{})
	if createPhaDeploymentOptions.LocationID != nil {
		body["location_id"] = createPhaDeploymentOptions.LocationID
	}
	if createPhaDeploymentOptions.PrimaryWorkspace != nil {
		body["primary_workspace"] = createPhaDeploymentOptions.PrimaryWorkspace
	}
	if createPhaDeploymentOptions.APIKey != nil {
		body["api_key"] = createPhaDeploymentOptions.APIKey
	}
	if createPhaDeploymentOptions.ClusterType != nil {
		body["cluster_type"] = createPhaDeploymentOptions.ClusterType
	}
	if createPhaDeploymentOptions.ConfigureType != nil {
		body["configure_type"] = createPhaDeploymentOptions.ConfigureType
	}
	if createPhaDeploymentOptions.PrimaryClusterNodes != nil {
		body["primary_cluster_nodes"] = createPhaDeploymentOptions.PrimaryClusterNodes
	}
	if createPhaDeploymentOptions.StandbyClusterNodes != nil {
		body["standby_cluster_nodes"] = createPhaDeploymentOptions.StandbyClusterNodes
	}
	if createPhaDeploymentOptions.PrimaryLocation != nil {
		body["primary_location"] = createPhaDeploymentOptions.PrimaryLocation
	}
	if createPhaDeploymentOptions.SecondaryLocation != nil {
		body["secondary_location"] = createPhaDeploymentOptions.SecondaryLocation
	}
	if createPhaDeploymentOptions.SecondaryWorkspace != nil {
		body["secondary_workspace"] = createPhaDeploymentOptions.SecondaryWorkspace
	}
	_, err = builder.SetBodyContentJSON(body)
	if err != nil {
		err = core.SDKErrorf(err, "", "set-json-body-error", common.GetComponentInfo())
		return
	}

	request, err := builder.Build()
	if err != nil {
		err = core.SDKErrorf(err, "", "build-error", common.GetComponentInfo())
		return
	}

	var rawResponse map[string]json.RawMessage
	response, err = powerhaAutomationService.Service.Request(request, &rawResponse)
	if err != nil {
		core.EnrichHTTPProblem(err, "create_pha_deployment", getServiceComponentInfo())
		err = core.SDKErrorf(err, "", "http-request-err", common.GetComponentInfo())
		return
	}
	if rawResponse != nil {
		err = core.UnmarshalModel(rawResponse, "", &result, UnmarshalPhaDeploymentResponse)
		if err != nil {
			err = core.SDKErrorf(err, "", "unmarshal-resp-error", common.GetComponentInfo())
			return
		}
		response.Result = result
	}

	return
}

// GetSupportedLocation : Get PowerVS locations
// Retrieves the list of PowerVS locations where PowerHA service is supported.
func (powerhaAutomationService *PowerhaAutomationServiceV1) GetSupportedLocation(getSupportedLocationOptions *GetSupportedLocationOptions) (result *PhaSupportedLocationsResponse, response *core.DetailedResponse, err error) {
	result, response, err = powerhaAutomationService.GetSupportedLocationWithContext(context.Background(), getSupportedLocationOptions)
	err = core.RepurposeSDKProblem(err, "")
	return
}

// GetSupportedLocationWithContext is an alternate form of the GetSupportedLocation method which supports a Context parameter
func (powerhaAutomationService *PowerhaAutomationServiceV1) GetSupportedLocationWithContext(ctx context.Context, getSupportedLocationOptions *GetSupportedLocationOptions) (result *PhaSupportedLocationsResponse, response *core.DetailedResponse, err error) {
	err = core.ValidateNotNil(getSupportedLocationOptions, "getSupportedLocationOptions cannot be nil")
	if err != nil {
		err = core.SDKErrorf(err, "", "unexpected-nil-param", common.GetComponentInfo())
		return
	}
	err = core.ValidateStruct(getSupportedLocationOptions, "getSupportedLocationOptions")
	if err != nil {
		err = core.SDKErrorf(err, "", "struct-validation-error", common.GetComponentInfo())
		return
	}

	pathParamsMap := map[string]string{
		"pha_instance_id": *getSupportedLocationOptions.PhaInstanceID,
	}

	builder := core.NewRequestBuilder(core.GET)
	builder = builder.WithContext(ctx)
	builder.EnableGzipCompression = powerhaAutomationService.GetEnableGzipCompression()
	_, err = builder.ResolveRequestURL(powerhaAutomationService.Service.Options.URL, `/powerha_automation/v1/supported_locations/{pha_instance_id}`, pathParamsMap)
	if err != nil {
		err = core.SDKErrorf(err, "", "url-resolve-error", common.GetComponentInfo())
		return
	}

	sdkHeaders := common.GetSdkHeaders("powerha_automation_service", "V1", "GetSupportedLocation")
	for headerName, headerValue := range sdkHeaders {
		builder.AddHeader(headerName, headerValue)
	}

	for headerName, headerValue := range getSupportedLocationOptions.Headers {
		builder.AddHeader(headerName, headerValue)
	}
	builder.AddHeader("Accept", "application/json")
	if getSupportedLocationOptions.IfNoneMatch != nil {
		builder.AddHeader("If-None-Match", fmt.Sprint(*getSupportedLocationOptions.IfNoneMatch))
	}

	request, err := builder.Build()
	if err != nil {
		err = core.SDKErrorf(err, "", "build-error", common.GetComponentInfo())
		return
	}

	var rawResponse map[string]json.RawMessage
	response, err = powerhaAutomationService.Service.Request(request, &rawResponse)
	if err != nil {
		core.EnrichHTTPProblem(err, "get_supported_location", getServiceComponentInfo())
		err = core.SDKErrorf(err, "", "http-request-err", common.GetComponentInfo())
		return
	}
	if rawResponse != nil {
		err = core.UnmarshalModel(rawResponse, "", &result, UnmarshalPhaSupportedLocationsResponse)
		if err != nil {
			err = core.SDKErrorf(err, "", "unmarshal-resp-error", common.GetComponentInfo())
			return
		}
		response.Result = result
	}

	return
}

// GetPhaAgentFileDownloadJobStatus : Get the Job status of the downloaded powerHA agent file
// Returns the current status of the job associated with a PowerHA agent file download. It indicates whether the
// download job is in running, completed, or failed, along with relevant metadata such as job ID, Job creation time and
// last updated time.
func (powerhaAutomationService *PowerhaAutomationServiceV1) GetPhaAgentFileDownloadJobStatus(getPhaAgentFileDownloadJobStatusOptions *GetPhaAgentFileDownloadJobStatusOptions) (result *PhaAgentJobStatusResponse, response *core.DetailedResponse, err error) {
	result, response, err = powerhaAutomationService.GetPhaAgentFileDownloadJobStatusWithContext(context.Background(), getPhaAgentFileDownloadJobStatusOptions)
	err = core.RepurposeSDKProblem(err, "")
	return
}

// GetPhaAgentFileDownloadJobStatusWithContext is an alternate form of the GetPhaAgentFileDownloadJobStatus method which supports a Context parameter
func (powerhaAutomationService *PowerhaAutomationServiceV1) GetPhaAgentFileDownloadJobStatusWithContext(ctx context.Context, getPhaAgentFileDownloadJobStatusOptions *GetPhaAgentFileDownloadJobStatusOptions) (result *PhaAgentJobStatusResponse, response *core.DetailedResponse, err error) {
	err = core.ValidateNotNil(getPhaAgentFileDownloadJobStatusOptions, "getPhaAgentFileDownloadJobStatusOptions cannot be nil")
	if err != nil {
		err = core.SDKErrorf(err, "", "unexpected-nil-param", common.GetComponentInfo())
		return
	}
	err = core.ValidateStruct(getPhaAgentFileDownloadJobStatusOptions, "getPhaAgentFileDownloadJobStatusOptions")
	if err != nil {
		err = core.SDKErrorf(err, "", "struct-validation-error", common.GetComponentInfo())
		return
	}

	pathParamsMap := map[string]string{
		"pha_instance_id": *getPhaAgentFileDownloadJobStatusOptions.PhaInstanceID,
		"pha_job_id":      *getPhaAgentFileDownloadJobStatusOptions.PhaJobID,
	}

	builder := core.NewRequestBuilder(core.GET)
	builder = builder.WithContext(ctx)
	builder.EnableGzipCompression = powerhaAutomationService.GetEnableGzipCompression()
	_, err = builder.ResolveRequestURL(powerhaAutomationService.Service.Options.URL, `/powerha_automation/v1/pha_agent/download/{pha_instance_id}/jobs/{pha_job_id}`, pathParamsMap)
	if err != nil {
		err = core.SDKErrorf(err, "", "url-resolve-error", common.GetComponentInfo())
		return
	}

	sdkHeaders := common.GetSdkHeaders("powerha_automation_service", "V1", "GetPhaAgentFileDownloadJobStatus")
	for headerName, headerValue := range sdkHeaders {
		builder.AddHeader(headerName, headerValue)
	}

	for headerName, headerValue := range getPhaAgentFileDownloadJobStatusOptions.Headers {
		builder.AddHeader(headerName, headerValue)
	}
	builder.AddHeader("Accept", "application/json")
	if getPhaAgentFileDownloadJobStatusOptions.AcceptLanguage != nil {
		builder.AddHeader("Accept-Language", fmt.Sprint(*getPhaAgentFileDownloadJobStatusOptions.AcceptLanguage))
	}
	if getPhaAgentFileDownloadJobStatusOptions.IfNoneMatch != nil {
		builder.AddHeader("If-None-Match", fmt.Sprint(*getPhaAgentFileDownloadJobStatusOptions.IfNoneMatch))
	}

	request, err := builder.Build()
	if err != nil {
		err = core.SDKErrorf(err, "", "build-error", common.GetComponentInfo())
		return
	}

	var rawResponse map[string]json.RawMessage
	response, err = powerhaAutomationService.Service.Request(request, &rawResponse)
	if err != nil {
		core.EnrichHTTPProblem(err, "get_pha_agent_file_download_job_status", getServiceComponentInfo())
		err = core.SDKErrorf(err, "", "http-request-err", common.GetComponentInfo())
		return
	}
	if rawResponse != nil {
		err = core.UnmarshalModel(rawResponse, "", &result, UnmarshalPhaAgentJobStatusResponse)
		if err != nil {
			err = core.SDKErrorf(err, "", "unmarshal-resp-error", common.GetComponentInfo())
			return
		}
		response.Result = result
	}

	return
}

// DownloadPhaAgentFile : Downloads PowerHA Agent file
// Validates the pvm instance and then creates a job for the download process, downloads the PowerHA agent file from the
// Cloud Object Storage (COS) location, and updates the job progress in real time. Users can use the job ID to query the
// download status, including whether the job is running, completed, or failed.
func (powerhaAutomationService *PowerhaAutomationServiceV1) DownloadPhaAgentFile(downloadPhaAgentFileOptions *DownloadPhaAgentFileOptions) (result io.ReadCloser, response *core.DetailedResponse, err error) {
	result, response, err = powerhaAutomationService.DownloadPhaAgentFileWithContext(context.Background(), downloadPhaAgentFileOptions)
	err = core.RepurposeSDKProblem(err, "")
	return
}

// DownloadPhaAgentFileWithContext is an alternate form of the DownloadPhaAgentFile method which supports a Context parameter
func (powerhaAutomationService *PowerhaAutomationServiceV1) DownloadPhaAgentFileWithContext(ctx context.Context, downloadPhaAgentFileOptions *DownloadPhaAgentFileOptions) (result io.ReadCloser, response *core.DetailedResponse, err error) {
	err = core.ValidateNotNil(downloadPhaAgentFileOptions, "downloadPhaAgentFileOptions cannot be nil")
	if err != nil {
		err = core.SDKErrorf(err, "", "unexpected-nil-param", common.GetComponentInfo())
		return
	}
	err = core.ValidateStruct(downloadPhaAgentFileOptions, "downloadPhaAgentFileOptions")
	if err != nil {
		err = core.SDKErrorf(err, "", "struct-validation-error", common.GetComponentInfo())
		return
	}

	pathParamsMap := map[string]string{
		"pha_instance_id": *downloadPhaAgentFileOptions.PhaInstanceID,
	}

	builder := core.NewRequestBuilder(core.GET)
	builder = builder.WithContext(ctx)
	builder.EnableGzipCompression = powerhaAutomationService.GetEnableGzipCompression()
	_, err = builder.ResolveRequestURL(powerhaAutomationService.Service.Options.URL, `/powerha_automation/v1/pha_agent/download/{pha_instance_id}`, pathParamsMap)
	if err != nil {
		err = core.SDKErrorf(err, "", "url-resolve-error", common.GetComponentInfo())
		return
	}

	sdkHeaders := common.GetSdkHeaders("powerha_automation_service", "V1", "DownloadPhaAgentFile")
	for headerName, headerValue := range sdkHeaders {
		builder.AddHeader(headerName, headerValue)
	}

	for headerName, headerValue := range downloadPhaAgentFileOptions.Headers {
		builder.AddHeader(headerName, headerValue)
	}
	builder.AddHeader("Accept", "application/octet-stream")
	if downloadPhaAgentFileOptions.AcceptLanguage != nil {
		builder.AddHeader("Accept-Language", fmt.Sprint(*downloadPhaAgentFileOptions.AcceptLanguage))
	}
	if downloadPhaAgentFileOptions.IfNoneMatch != nil {
		builder.AddHeader("If-None-Match", fmt.Sprint(*downloadPhaAgentFileOptions.IfNoneMatch))
	}

	request, err := builder.Build()
	if err != nil {
		err = core.SDKErrorf(err, "", "build-error", common.GetComponentInfo())
		return
	}

	response, err = powerhaAutomationService.Service.Request(request, &result)
	if err != nil {
		core.EnrichHTTPProblem(err, "download_pha_agent_file", getServiceComponentInfo())
		err = core.SDKErrorf(err, "", "http-request-err", common.GetComponentInfo())
		return
	}

	return
}
func getServiceComponentInfo() *core.ProblemComponent {
	return core.NewProblemComponent(DefaultServiceName, "1.0.0")
}

// APIKeyResponse : Response containing details of a stored API key.
type APIKeyResponse struct {
	// Status of the API key retrieval request.
	Status *string `json:"status" validate:"required"`

	// Unique identifier for the API key record.
	ID *string `json:"id" validate:"required"`
}

// UnmarshalAPIKeyResponse unmarshals an instance of APIKeyResponse from the specified map of raw messages.
func UnmarshalAPIKeyResponse(m map[string]json.RawMessage, result interface{}) (err error) {
	obj := new(APIKeyResponse)
	err = core.UnmarshalPrimitive(m, "status", &obj.Status)
	if err != nil {
		err = core.SDKErrorf(err, "", "status-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "id", &obj.ID)
	if err != nil {
		err = core.SDKErrorf(err, "", "id-error", common.GetComponentInfo())
		return
	}
	reflect.ValueOf(result).Elem().Set(reflect.ValueOf(obj))
	return
}

// ClusterNodeInfo : Information about a cluster node participating in the PHA environment.
type ClusterNodeInfo struct {
	// Status of the PHA agent running on the node.
	AgentStatus *string `json:"agent_status,omitempty"`

	// Number of CPU cores allocated to the node.
	Cores *float32 `json:"cores,omitempty"`

	// IP address assigned to the virtual machine.
	IPAddress *string `json:"ip_address,omitempty"`

	// Memory allocated to the virtual machine in MB or GB.
	Memory *int64 `json:"memory,omitempty"`

	// PowerHA version level installed on the node.
	PhaLevel *string `json:"pha_level,omitempty"`

	// Region where the virtual machine is deployed.
	Region *string `json:"region,omitempty"`

	// Unique identifier of the virtual machine.
	VMID *string `json:"vm_id,omitempty"`

	// Name of the virtual machine.
	VMName *string `json:"vm_name,omitempty"`

	// Current operational status of the virtual machine.
	VMStatus *string `json:"vm_status,omitempty"`

	// Workspace identifier associated with the node.
	WorkspaceID *string `json:"workspace_id,omitempty"`
}

// UnmarshalClusterNodeInfo unmarshals an instance of ClusterNodeInfo from the specified map of raw messages.
func UnmarshalClusterNodeInfo(m map[string]json.RawMessage, result interface{}) (err error) {
	obj := new(ClusterNodeInfo)
	err = core.UnmarshalPrimitive(m, "agent_status", &obj.AgentStatus)
	if err != nil {
		err = core.SDKErrorf(err, "", "agent_status-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "cores", &obj.Cores)
	if err != nil {
		err = core.SDKErrorf(err, "", "cores-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "ip_address", &obj.IPAddress)
	if err != nil {
		err = core.SDKErrorf(err, "", "ip_address-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "memory", &obj.Memory)
	if err != nil {
		err = core.SDKErrorf(err, "", "memory-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "pha_level", &obj.PhaLevel)
	if err != nil {
		err = core.SDKErrorf(err, "", "pha_level-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "region", &obj.Region)
	if err != nil {
		err = core.SDKErrorf(err, "", "region-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "vm_id", &obj.VMID)
	if err != nil {
		err = core.SDKErrorf(err, "", "vm_id-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "vm_name", &obj.VMName)
	if err != nil {
		err = core.SDKErrorf(err, "", "vm_name-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "vm_status", &obj.VMStatus)
	if err != nil {
		err = core.SDKErrorf(err, "", "vm_status-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "workspace_id", &obj.WorkspaceID)
	if err != nil {
		err = core.SDKErrorf(err, "", "workspace_id-error", common.GetComponentInfo())
		return
	}
	reflect.ValueOf(result).Elem().Set(reflect.ValueOf(obj))
	return
}

// ClusterNodeResponse : Response schema for retrieving cluster node information.
type ClusterNodeResponse struct {
	// Identifier for this cluster node response.
	ID *string `json:"id,omitempty"`

	// Details of the primary cluster nodes.
	PrimaryNodeDetails []NodeDetail `json:"primary_node_details" validate:"required"`

	// Details of the secondary cluster nodes.
	SecondaryNodeDetails []NodeDetail `json:"secondary_node_details" validate:"required"`
}

// UnmarshalClusterNodeResponse unmarshals an instance of ClusterNodeResponse from the specified map of raw messages.
func UnmarshalClusterNodeResponse(m map[string]json.RawMessage, result interface{}) (err error) {
	obj := new(ClusterNodeResponse)
	err = core.UnmarshalPrimitive(m, "id", &obj.ID)
	if err != nil {
		err = core.SDKErrorf(err, "", "id-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalModel(m, "primary_node_details", &obj.PrimaryNodeDetails, UnmarshalNodeDetail)
	if err != nil {
		err = core.SDKErrorf(err, "", "primary_node_details-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalModel(m, "secondary_node_details", &obj.SecondaryNodeDetails, UnmarshalNodeDetail)
	if err != nil {
		err = core.SDKErrorf(err, "", "secondary_node_details-error", common.GetComponentInfo())
		return
	}
	reflect.ValueOf(result).Elem().Set(reflect.ValueOf(obj))
	return
}

// CreateAPIKeyOptions : The CreateAPIKey options.
type CreateAPIKeyOptions struct {
	// Unique identifier of the provisioned instance.
	PhaInstanceID *string `json:"pha_instance_id" validate:"required,ne="`

	// The API key to be stored or registered.
	APIKey *string `json:"api_key,omitempty"`

	// The language requested for the return document.
	AcceptLanguage *string `json:"Accept-Language,omitempty"`

	// Allows users to set headers on API requests.
	Headers map[string]string
}

// NewCreateAPIKeyOptions : Instantiate CreateAPIKeyOptions
func (*PowerhaAutomationServiceV1) NewCreateAPIKeyOptions(phaInstanceID string) *CreateAPIKeyOptions {
	return &CreateAPIKeyOptions{
		PhaInstanceID: core.StringPtr(phaInstanceID),
	}
}

// SetPhaInstanceID : Allow user to set PhaInstanceID
func (_options *CreateAPIKeyOptions) SetPhaInstanceID(phaInstanceID string) *CreateAPIKeyOptions {
	_options.PhaInstanceID = core.StringPtr(phaInstanceID)
	return _options
}

// SetAPIKey : Allow user to set APIKey
func (_options *CreateAPIKeyOptions) SetAPIKey(apiKey string) *CreateAPIKeyOptions {
	_options.APIKey = core.StringPtr(apiKey)
	return _options
}

// SetAcceptLanguage : Allow user to set AcceptLanguage
func (_options *CreateAPIKeyOptions) SetAcceptLanguage(acceptLanguage string) *CreateAPIKeyOptions {
	_options.AcceptLanguage = core.StringPtr(acceptLanguage)
	return _options
}

// SetHeaders : Allow user to set Headers
func (options *CreateAPIKeyOptions) SetHeaders(param map[string]string) *CreateAPIKeyOptions {
	options.Headers = param
	return options
}

// CreateClusterNodeOptions : The CreateClusterNode options.
type CreateClusterNodeOptions struct {
	// Unique identifier of the provisioned instance.
	PhaInstanceID *string `json:"pha_instance_id" validate:"required,ne="`

	// List of primary cluster node VM IDs.
	PrimaryClusterNodes []string `json:"primary_cluster_nodes" validate:"required"`

	// List of secondary cluster node VM IDs.
	SecondaryClusterNodes []string `json:"secondary_cluster_nodes,omitempty"`

	// The language requested for the return document.
	AcceptLanguage *string `json:"Accept-Language,omitempty"`

	// ETag for conditional requests (optional).
	IfNoneMatch *string `json:"If-None-Match,omitempty"`

	// Allows users to set headers on API requests.
	Headers map[string]string
}

// NewCreateClusterNodeOptions : Instantiate CreateClusterNodeOptions
func (*PowerhaAutomationServiceV1) NewCreateClusterNodeOptions(phaInstanceID string, primaryClusterNodes []string) *CreateClusterNodeOptions {
	return &CreateClusterNodeOptions{
		PhaInstanceID:       core.StringPtr(phaInstanceID),
		PrimaryClusterNodes: primaryClusterNodes,
	}
}

// SetPhaInstanceID : Allow user to set PhaInstanceID
func (_options *CreateClusterNodeOptions) SetPhaInstanceID(phaInstanceID string) *CreateClusterNodeOptions {
	_options.PhaInstanceID = core.StringPtr(phaInstanceID)
	return _options
}

// SetPrimaryClusterNodes : Allow user to set PrimaryClusterNodes
func (_options *CreateClusterNodeOptions) SetPrimaryClusterNodes(primaryClusterNodes []string) *CreateClusterNodeOptions {
	_options.PrimaryClusterNodes = primaryClusterNodes
	return _options
}

// SetSecondaryClusterNodes : Allow user to set SecondaryClusterNodes
func (_options *CreateClusterNodeOptions) SetSecondaryClusterNodes(secondaryClusterNodes []string) *CreateClusterNodeOptions {
	_options.SecondaryClusterNodes = secondaryClusterNodes
	return _options
}

// SetAcceptLanguage : Allow user to set AcceptLanguage
func (_options *CreateClusterNodeOptions) SetAcceptLanguage(acceptLanguage string) *CreateClusterNodeOptions {
	_options.AcceptLanguage = core.StringPtr(acceptLanguage)
	return _options
}

// SetIfNoneMatch : Allow user to set IfNoneMatch
func (_options *CreateClusterNodeOptions) SetIfNoneMatch(ifNoneMatch string) *CreateClusterNodeOptions {
	_options.IfNoneMatch = core.StringPtr(ifNoneMatch)
	return _options
}

// SetHeaders : Allow user to set Headers
func (options *CreateClusterNodeOptions) SetHeaders(param map[string]string) *CreateClusterNodeOptions {
	options.Headers = param
	return options
}

// CreatePhaDeploymentOptions : The CreatePhaDeployment options.
type CreatePhaDeploymentOptions struct {
	// Unique identifier of the provisioned instance.
	PhaInstanceID *string `json:"pha_instance_id" validate:"required,ne="`

	// Identifier for the deployment location.
	LocationID *string `json:"location_id" validate:"required"`

	// Primary workspace identifier.
	PrimaryWorkspace *string `json:"primary_workspace" validate:"required"`

	// The API key associated with the request.
	APIKey *string `json:"api_key,omitempty"`

	// Type of PowerHA cluster being deployed.
	ClusterType *string `json:"cluster_type,omitempty"`

	// Configuration type for the deployment.
	ConfigureType *string `json:"configure_type,omitempty"`

	// List of primary cluster node VM IDs.
	PrimaryClusterNodes []string `json:"primary_cluster_nodes,omitempty"`

	// List of standby cluster node VM IDs.
	StandbyClusterNodes []string `json:"standby_cluster_nodes,omitempty"`

	// Location identifier for the primary cluster.
	PrimaryLocation *string `json:"primary_location,omitempty"`

	// Location identifier for the secondary cluster.
	SecondaryLocation *string `json:"secondary_location,omitempty"`

	// Secondary workspace identifier.
	SecondaryWorkspace *string `json:"secondary_workspace,omitempty"`

	// The language requested for the return document.
	AcceptLanguage *string `json:"Accept-Language,omitempty"`

	// ETag for conditional requests (optional).
	IfNoneMatch *string `json:"If-None-Match,omitempty"`

	// Allows users to set headers on API requests.
	Headers map[string]string
}

// NewCreatePhaDeploymentOptions : Instantiate CreatePhaDeploymentOptions
func (*PowerhaAutomationServiceV1) NewCreatePhaDeploymentOptions(phaInstanceID string, locationID string, primaryWorkspace string) *CreatePhaDeploymentOptions {
	return &CreatePhaDeploymentOptions{
		PhaInstanceID:    core.StringPtr(phaInstanceID),
		LocationID:       core.StringPtr(locationID),
		PrimaryWorkspace: core.StringPtr(primaryWorkspace),
	}
}

// SetPhaInstanceID : Allow user to set PhaInstanceID
func (_options *CreatePhaDeploymentOptions) SetPhaInstanceID(phaInstanceID string) *CreatePhaDeploymentOptions {
	_options.PhaInstanceID = core.StringPtr(phaInstanceID)
	return _options
}

// SetLocationID : Allow user to set LocationID
func (_options *CreatePhaDeploymentOptions) SetLocationID(locationID string) *CreatePhaDeploymentOptions {
	_options.LocationID = core.StringPtr(locationID)
	return _options
}

// SetPrimaryWorkspace : Allow user to set PrimaryWorkspace
func (_options *CreatePhaDeploymentOptions) SetPrimaryWorkspace(primaryWorkspace string) *CreatePhaDeploymentOptions {
	_options.PrimaryWorkspace = core.StringPtr(primaryWorkspace)
	return _options
}

// SetAPIKey : Allow user to set APIKey
func (_options *CreatePhaDeploymentOptions) SetAPIKey(apiKey string) *CreatePhaDeploymentOptions {
	_options.APIKey = core.StringPtr(apiKey)
	return _options
}

// SetClusterType : Allow user to set ClusterType
func (_options *CreatePhaDeploymentOptions) SetClusterType(clusterType string) *CreatePhaDeploymentOptions {
	_options.ClusterType = core.StringPtr(clusterType)
	return _options
}

// SetConfigureType : Allow user to set ConfigureType
func (_options *CreatePhaDeploymentOptions) SetConfigureType(configureType string) *CreatePhaDeploymentOptions {
	_options.ConfigureType = core.StringPtr(configureType)
	return _options
}

// SetPrimaryClusterNodes : Allow user to set PrimaryClusterNodes
func (_options *CreatePhaDeploymentOptions) SetPrimaryClusterNodes(primaryClusterNodes []string) *CreatePhaDeploymentOptions {
	_options.PrimaryClusterNodes = primaryClusterNodes
	return _options
}

// SetStandbyClusterNodes : Allow user to set StandbyClusterNodes
func (_options *CreatePhaDeploymentOptions) SetStandbyClusterNodes(standbyClusterNodes []string) *CreatePhaDeploymentOptions {
	_options.StandbyClusterNodes = standbyClusterNodes
	return _options
}

// SetPrimaryLocation : Allow user to set PrimaryLocation
func (_options *CreatePhaDeploymentOptions) SetPrimaryLocation(primaryLocation string) *CreatePhaDeploymentOptions {
	_options.PrimaryLocation = core.StringPtr(primaryLocation)
	return _options
}

// SetSecondaryLocation : Allow user to set SecondaryLocation
func (_options *CreatePhaDeploymentOptions) SetSecondaryLocation(secondaryLocation string) *CreatePhaDeploymentOptions {
	_options.SecondaryLocation = core.StringPtr(secondaryLocation)
	return _options
}

// SetSecondaryWorkspace : Allow user to set SecondaryWorkspace
func (_options *CreatePhaDeploymentOptions) SetSecondaryWorkspace(secondaryWorkspace string) *CreatePhaDeploymentOptions {
	_options.SecondaryWorkspace = core.StringPtr(secondaryWorkspace)
	return _options
}

// SetAcceptLanguage : Allow user to set AcceptLanguage
func (_options *CreatePhaDeploymentOptions) SetAcceptLanguage(acceptLanguage string) *CreatePhaDeploymentOptions {
	_options.AcceptLanguage = core.StringPtr(acceptLanguage)
	return _options
}

// SetIfNoneMatch : Allow user to set IfNoneMatch
func (_options *CreatePhaDeploymentOptions) SetIfNoneMatch(ifNoneMatch string) *CreatePhaDeploymentOptions {
	_options.IfNoneMatch = core.StringPtr(ifNoneMatch)
	return _options
}

// SetHeaders : Allow user to set Headers
func (options *CreatePhaDeploymentOptions) SetHeaders(param map[string]string) *CreatePhaDeploymentOptions {
	options.Headers = param
	return options
}

// DeleteClusterNodeOptions : The DeleteClusterNode options.
type DeleteClusterNodeOptions struct {
	// Unique identifier of the provisioned instance.
	PhaInstanceID *string `json:"pha_instance_id" validate:"required,ne="`

	// vm ID of workspace.
	VMID *string `json:"vm_id" validate:"required"`

	// ETag for conditional requests (optional).
	IfNoneMatch *string `json:"If-None-Match,omitempty"`

	// Allows users to set headers on API requests.
	Headers map[string]string
}

// NewDeleteClusterNodeOptions : Instantiate DeleteClusterNodeOptions
func (*PowerhaAutomationServiceV1) NewDeleteClusterNodeOptions(phaInstanceID string, vmID string) *DeleteClusterNodeOptions {
	return &DeleteClusterNodeOptions{
		PhaInstanceID: core.StringPtr(phaInstanceID),
		VMID:          core.StringPtr(vmID),
	}
}

// SetPhaInstanceID : Allow user to set PhaInstanceID
func (_options *DeleteClusterNodeOptions) SetPhaInstanceID(phaInstanceID string) *DeleteClusterNodeOptions {
	_options.PhaInstanceID = core.StringPtr(phaInstanceID)
	return _options
}

// SetVMID : Allow user to set VMID
func (_options *DeleteClusterNodeOptions) SetVMID(vmID string) *DeleteClusterNodeOptions {
	_options.VMID = core.StringPtr(vmID)
	return _options
}

// SetIfNoneMatch : Allow user to set IfNoneMatch
func (_options *DeleteClusterNodeOptions) SetIfNoneMatch(ifNoneMatch string) *DeleteClusterNodeOptions {
	_options.IfNoneMatch = core.StringPtr(ifNoneMatch)
	return _options
}

// SetHeaders : Allow user to set Headers
func (options *DeleteClusterNodeOptions) SetHeaders(param map[string]string) *DeleteClusterNodeOptions {
	options.Headers = param
	return options
}

// DownloadPhaAgentFileOptions : The DownloadPhaAgentFile options.
type DownloadPhaAgentFileOptions struct {
	// Unique identifier of the provisioned instance.
	PhaInstanceID *string `json:"pha_instance_id" validate:"required,ne="`

	// The language requested for the return document.
	AcceptLanguage *string `json:"Accept-Language,omitempty"`

	// ETag for conditional requests (optional).
	IfNoneMatch *string `json:"If-None-Match,omitempty"`

	// Allows users to set headers on API requests.
	Headers map[string]string
}

// NewDownloadPhaAgentFileOptions : Instantiate DownloadPhaAgentFileOptions
func (*PowerhaAutomationServiceV1) NewDownloadPhaAgentFileOptions(phaInstanceID string) *DownloadPhaAgentFileOptions {
	return &DownloadPhaAgentFileOptions{
		PhaInstanceID: core.StringPtr(phaInstanceID),
	}
}

// SetPhaInstanceID : Allow user to set PhaInstanceID
func (_options *DownloadPhaAgentFileOptions) SetPhaInstanceID(phaInstanceID string) *DownloadPhaAgentFileOptions {
	_options.PhaInstanceID = core.StringPtr(phaInstanceID)
	return _options
}

// SetAcceptLanguage : Allow user to set AcceptLanguage
func (_options *DownloadPhaAgentFileOptions) SetAcceptLanguage(acceptLanguage string) *DownloadPhaAgentFileOptions {
	_options.AcceptLanguage = core.StringPtr(acceptLanguage)
	return _options
}

// SetIfNoneMatch : Allow user to set IfNoneMatch
func (_options *DownloadPhaAgentFileOptions) SetIfNoneMatch(ifNoneMatch string) *DownloadPhaAgentFileOptions {
	_options.IfNoneMatch = core.StringPtr(ifNoneMatch)
	return _options
}

// SetHeaders : Allow user to set Headers
func (options *DownloadPhaAgentFileOptions) SetHeaders(param map[string]string) *DownloadPhaAgentFileOptions {
	options.Headers = param
	return options
}

// GetAPIKeyOptions : The GetAPIKey options.
type GetAPIKeyOptions struct {
	// Unique identifier of the provisioned instance.
	PhaInstanceID *string `json:"pha_instance_id" validate:"required,ne="`

	// The language requested for the return document.
	AcceptLanguage *string `json:"Accept-Language,omitempty"`

	// ETag for conditional requests (optional).
	IfNoneMatch *string `json:"If-None-Match,omitempty"`

	// Allows users to set headers on API requests.
	Headers map[string]string
}

// NewGetAPIKeyOptions : Instantiate GetAPIKeyOptions
func (*PowerhaAutomationServiceV1) NewGetAPIKeyOptions(phaInstanceID string) *GetAPIKeyOptions {
	return &GetAPIKeyOptions{
		PhaInstanceID: core.StringPtr(phaInstanceID),
	}
}

// SetPhaInstanceID : Allow user to set PhaInstanceID
func (_options *GetAPIKeyOptions) SetPhaInstanceID(phaInstanceID string) *GetAPIKeyOptions {
	_options.PhaInstanceID = core.StringPtr(phaInstanceID)
	return _options
}

// SetAcceptLanguage : Allow user to set AcceptLanguage
func (_options *GetAPIKeyOptions) SetAcceptLanguage(acceptLanguage string) *GetAPIKeyOptions {
	_options.AcceptLanguage = core.StringPtr(acceptLanguage)
	return _options
}

// SetIfNoneMatch : Allow user to set IfNoneMatch
func (_options *GetAPIKeyOptions) SetIfNoneMatch(ifNoneMatch string) *GetAPIKeyOptions {
	_options.IfNoneMatch = core.StringPtr(ifNoneMatch)
	return _options
}

// SetHeaders : Allow user to set Headers
func (options *GetAPIKeyOptions) SetHeaders(param map[string]string) *GetAPIKeyOptions {
	options.Headers = param
	return options
}

// GetClusterNodeOptions : The GetClusterNode options.
type GetClusterNodeOptions struct {
	// Unique identifier of the provisioned instance.
	PhaInstanceID *string `json:"pha_instance_id" validate:"required,ne="`

	// ETag for conditional requests (optional).
	IfNoneMatch *string `json:"If-None-Match,omitempty"`

	// Allows users to set headers on API requests.
	Headers map[string]string
}

// NewGetClusterNodeOptions : Instantiate GetClusterNodeOptions
func (*PowerhaAutomationServiceV1) NewGetClusterNodeOptions(phaInstanceID string) *GetClusterNodeOptions {
	return &GetClusterNodeOptions{
		PhaInstanceID: core.StringPtr(phaInstanceID),
	}
}

// SetPhaInstanceID : Allow user to set PhaInstanceID
func (_options *GetClusterNodeOptions) SetPhaInstanceID(phaInstanceID string) *GetClusterNodeOptions {
	_options.PhaInstanceID = core.StringPtr(phaInstanceID)
	return _options
}

// SetIfNoneMatch : Allow user to set IfNoneMatch
func (_options *GetClusterNodeOptions) SetIfNoneMatch(ifNoneMatch string) *GetClusterNodeOptions {
	_options.IfNoneMatch = core.StringPtr(ifNoneMatch)
	return _options
}

// SetHeaders : Allow user to set Headers
func (options *GetClusterNodeOptions) SetHeaders(param map[string]string) *GetClusterNodeOptions {
	options.Headers = param
	return options
}

// GetPhaAgentFileDownloadJobStatusOptions : The GetPhaAgentFileDownloadJobStatus options.
type GetPhaAgentFileDownloadJobStatusOptions struct {
	// Unique identifier of the provisioned instance.
	PhaInstanceID *string `json:"pha_instance_id" validate:"required,ne="`

	// Unique ID to track the pha agent file download.
	PhaJobID *string `json:"pha_job_id" validate:"required,ne="`

	// The language requested for the return document.
	AcceptLanguage *string `json:"Accept-Language,omitempty"`

	// ETag for conditional requests (optional).
	IfNoneMatch *string `json:"If-None-Match,omitempty"`

	// Allows users to set headers on API requests.
	Headers map[string]string
}

// NewGetPhaAgentFileDownloadJobStatusOptions : Instantiate GetPhaAgentFileDownloadJobStatusOptions
func (*PowerhaAutomationServiceV1) NewGetPhaAgentFileDownloadJobStatusOptions(phaInstanceID string, phaJobID string) *GetPhaAgentFileDownloadJobStatusOptions {
	return &GetPhaAgentFileDownloadJobStatusOptions{
		PhaInstanceID: core.StringPtr(phaInstanceID),
		PhaJobID:      core.StringPtr(phaJobID),
	}
}

// SetPhaInstanceID : Allow user to set PhaInstanceID
func (_options *GetPhaAgentFileDownloadJobStatusOptions) SetPhaInstanceID(phaInstanceID string) *GetPhaAgentFileDownloadJobStatusOptions {
	_options.PhaInstanceID = core.StringPtr(phaInstanceID)
	return _options
}

// SetPhaJobID : Allow user to set PhaJobID
func (_options *GetPhaAgentFileDownloadJobStatusOptions) SetPhaJobID(phaJobID string) *GetPhaAgentFileDownloadJobStatusOptions {
	_options.PhaJobID = core.StringPtr(phaJobID)
	return _options
}

// SetAcceptLanguage : Allow user to set AcceptLanguage
func (_options *GetPhaAgentFileDownloadJobStatusOptions) SetAcceptLanguage(acceptLanguage string) *GetPhaAgentFileDownloadJobStatusOptions {
	_options.AcceptLanguage = core.StringPtr(acceptLanguage)
	return _options
}

// SetIfNoneMatch : Allow user to set IfNoneMatch
func (_options *GetPhaAgentFileDownloadJobStatusOptions) SetIfNoneMatch(ifNoneMatch string) *GetPhaAgentFileDownloadJobStatusOptions {
	_options.IfNoneMatch = core.StringPtr(ifNoneMatch)
	return _options
}

// SetHeaders : Allow user to set Headers
func (options *GetPhaAgentFileDownloadJobStatusOptions) SetHeaders(param map[string]string) *GetPhaAgentFileDownloadJobStatusOptions {
	options.Headers = param
	return options
}

// GetPhaDeploymentOptions : The GetPhaDeployment options.
type GetPhaDeploymentOptions struct {
	// Unique identifier of the provisioned instance.
	PhaInstanceID *string `json:"pha_instance_id" validate:"required,ne="`

	// ETag for conditional requests (optional).
	IfNoneMatch *string `json:"If-None-Match,omitempty"`

	// Allows users to set headers on API requests.
	Headers map[string]string
}

// NewGetPhaDeploymentOptions : Instantiate GetPhaDeploymentOptions
func (*PowerhaAutomationServiceV1) NewGetPhaDeploymentOptions(phaInstanceID string) *GetPhaDeploymentOptions {
	return &GetPhaDeploymentOptions{
		PhaInstanceID: core.StringPtr(phaInstanceID),
	}
}

// SetPhaInstanceID : Allow user to set PhaInstanceID
func (_options *GetPhaDeploymentOptions) SetPhaInstanceID(phaInstanceID string) *GetPhaDeploymentOptions {
	_options.PhaInstanceID = core.StringPtr(phaInstanceID)
	return _options
}

// SetIfNoneMatch : Allow user to set IfNoneMatch
func (_options *GetPhaDeploymentOptions) SetIfNoneMatch(ifNoneMatch string) *GetPhaDeploymentOptions {
	_options.IfNoneMatch = core.StringPtr(ifNoneMatch)
	return _options
}

// SetHeaders : Allow user to set Headers
func (options *GetPhaDeploymentOptions) SetHeaders(param map[string]string) *GetPhaDeploymentOptions {
	options.Headers = param
	return options
}

// GetPhaLastOperationOptions : The GetPhaLastOperation options.
type GetPhaLastOperationOptions struct {
	// Unique identifier of the provisioned instance.
	PhaInstanceID *string `json:"pha_instance_id" validate:"required,ne="`

	// The language requested for the return document.
	AcceptLanguage *string `json:"Accept-Language,omitempty"`

	// ETag for conditional requests (optional).
	IfNoneMatch *string `json:"If-None-Match,omitempty"`

	// Allows users to set headers on API requests.
	Headers map[string]string
}

// NewGetPhaLastOperationOptions : Instantiate GetPhaLastOperationOptions
func (*PowerhaAutomationServiceV1) NewGetPhaLastOperationOptions(phaInstanceID string) *GetPhaLastOperationOptions {
	return &GetPhaLastOperationOptions{
		PhaInstanceID: core.StringPtr(phaInstanceID),
	}
}

// SetPhaInstanceID : Allow user to set PhaInstanceID
func (_options *GetPhaLastOperationOptions) SetPhaInstanceID(phaInstanceID string) *GetPhaLastOperationOptions {
	_options.PhaInstanceID = core.StringPtr(phaInstanceID)
	return _options
}

// SetAcceptLanguage : Allow user to set AcceptLanguage
func (_options *GetPhaLastOperationOptions) SetAcceptLanguage(acceptLanguage string) *GetPhaLastOperationOptions {
	_options.AcceptLanguage = core.StringPtr(acceptLanguage)
	return _options
}

// SetIfNoneMatch : Allow user to set IfNoneMatch
func (_options *GetPhaLastOperationOptions) SetIfNoneMatch(ifNoneMatch string) *GetPhaLastOperationOptions {
	_options.IfNoneMatch = core.StringPtr(ifNoneMatch)
	return _options
}

// SetHeaders : Allow user to set Headers
func (options *GetPhaLastOperationOptions) SetHeaders(param map[string]string) *GetPhaLastOperationOptions {
	options.Headers = param
	return options
}

// GetPowervsWorkspaceOptions : The GetPowervsWorkspace options.
type GetPowervsWorkspaceOptions struct {
	// Unique identifier of the provisioned instance.
	PhaInstanceID *string `json:"pha_instance_id" validate:"required,ne="`

	// Location ID value.
	LocationID *string `json:"location_id" validate:"required"`

	// The language requested for the return document.
	AcceptLanguage *string `json:"Accept-Language,omitempty"`

	// ETag for conditional requests (optional).
	IfNoneMatch *string `json:"If-None-Match,omitempty"`

	// Allows users to set headers on API requests.
	Headers map[string]string
}

// NewGetPowervsWorkspaceOptions : Instantiate GetPowervsWorkspaceOptions
func (*PowerhaAutomationServiceV1) NewGetPowervsWorkspaceOptions(phaInstanceID string, locationID string) *GetPowervsWorkspaceOptions {
	return &GetPowervsWorkspaceOptions{
		PhaInstanceID: core.StringPtr(phaInstanceID),
		LocationID:    core.StringPtr(locationID),
	}
}

// SetPhaInstanceID : Allow user to set PhaInstanceID
func (_options *GetPowervsWorkspaceOptions) SetPhaInstanceID(phaInstanceID string) *GetPowervsWorkspaceOptions {
	_options.PhaInstanceID = core.StringPtr(phaInstanceID)
	return _options
}

// SetLocationID : Allow user to set LocationID
func (_options *GetPowervsWorkspaceOptions) SetLocationID(locationID string) *GetPowervsWorkspaceOptions {
	_options.LocationID = core.StringPtr(locationID)
	return _options
}

// SetAcceptLanguage : Allow user to set AcceptLanguage
func (_options *GetPowervsWorkspaceOptions) SetAcceptLanguage(acceptLanguage string) *GetPowervsWorkspaceOptions {
	_options.AcceptLanguage = core.StringPtr(acceptLanguage)
	return _options
}

// SetIfNoneMatch : Allow user to set IfNoneMatch
func (_options *GetPowervsWorkspaceOptions) SetIfNoneMatch(ifNoneMatch string) *GetPowervsWorkspaceOptions {
	_options.IfNoneMatch = core.StringPtr(ifNoneMatch)
	return _options
}

// SetHeaders : Allow user to set Headers
func (options *GetPowervsWorkspaceOptions) SetHeaders(param map[string]string) *GetPowervsWorkspaceOptions {
	options.Headers = param
	return options
}

// GetSupportedLocationOptions : The GetSupportedLocation options.
type GetSupportedLocationOptions struct {
	// Unique identifier of the provisioned instance.
	PhaInstanceID *string `json:"pha_instance_id" validate:"required,ne="`

	// ETag for conditional requests (optional).
	IfNoneMatch *string `json:"If-None-Match,omitempty"`

	// Allows users to set headers on API requests.
	Headers map[string]string
}

// NewGetSupportedLocationOptions : Instantiate GetSupportedLocationOptions
func (*PowerhaAutomationServiceV1) NewGetSupportedLocationOptions(phaInstanceID string) *GetSupportedLocationOptions {
	return &GetSupportedLocationOptions{
		PhaInstanceID: core.StringPtr(phaInstanceID),
	}
}

// SetPhaInstanceID : Allow user to set PhaInstanceID
func (_options *GetSupportedLocationOptions) SetPhaInstanceID(phaInstanceID string) *GetSupportedLocationOptions {
	_options.PhaInstanceID = core.StringPtr(phaInstanceID)
	return _options
}

// SetIfNoneMatch : Allow user to set IfNoneMatch
func (_options *GetSupportedLocationOptions) SetIfNoneMatch(ifNoneMatch string) *GetSupportedLocationOptions {
	_options.IfNoneMatch = core.StringPtr(ifNoneMatch)
	return _options
}

// SetHeaders : Allow user to set Headers
func (options *GetSupportedLocationOptions) SetHeaders(param map[string]string) *GetSupportedLocationOptions {
	options.Headers = param
	return options
}

// NodeDetail : Details of a virtual machine (VM) participating in the cluster.
type NodeDetail struct {
	// Status of the PHA agent running on the node.
	AgentStatus *string `json:"agent_status,omitempty"`

	// Number of CPU cores allocated to the VM.
	Cores *float32 `json:"cores,omitempty"`

	// List of IP addresses assigned to the VM.
	IPAddresses []string `json:"ip_addresses" validate:"required"`

	// Amount of memory allocated to the VM (in GB).
	Memory *float32 `json:"memory,omitempty"`

	// PowerHA version level installed on the node.
	PhaLevel *string `json:"pha_level,omitempty"`

	// Region where the VM is deployed.
	Region *string `json:"region,omitempty"`

	// Unique identifier of the VM.
	VMID *string `json:"vm_id,omitempty"`

	// Name of the VM.
	VMName *string `json:"vm_name,omitempty"`

	// Current status of the VM.
	VMStatus *string `json:"vm_status,omitempty"`

	// ID of the workspace associated with the VM.
	WorkspaceID *string `json:"workspace_id,omitempty"`
}

// UnmarshalNodeDetail unmarshals an instance of NodeDetail from the specified map of raw messages.
func UnmarshalNodeDetail(m map[string]json.RawMessage, result interface{}) (err error) {
	obj := new(NodeDetail)
	err = core.UnmarshalPrimitive(m, "agent_status", &obj.AgentStatus)
	if err != nil {
		err = core.SDKErrorf(err, "", "agent_status-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "cores", &obj.Cores)
	if err != nil {
		err = core.SDKErrorf(err, "", "cores-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "ip_addresses", &obj.IPAddresses)
	if err != nil {
		err = core.SDKErrorf(err, "", "ip_addresses-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "memory", &obj.Memory)
	if err != nil {
		err = core.SDKErrorf(err, "", "memory-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "pha_level", &obj.PhaLevel)
	if err != nil {
		err = core.SDKErrorf(err, "", "pha_level-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "region", &obj.Region)
	if err != nil {
		err = core.SDKErrorf(err, "", "region-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "vm_id", &obj.VMID)
	if err != nil {
		err = core.SDKErrorf(err, "", "vm_id-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "vm_name", &obj.VMName)
	if err != nil {
		err = core.SDKErrorf(err, "", "vm_name-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "vm_status", &obj.VMStatus)
	if err != nil {
		err = core.SDKErrorf(err, "", "vm_status-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "workspace_id", &obj.WorkspaceID)
	if err != nil {
		err = core.SDKErrorf(err, "", "workspace_id-error", common.GetComponentInfo())
		return
	}
	reflect.ValueOf(result).Elem().Set(reflect.ValueOf(obj))
	return
}

// PhaAgentJobStatusResponse : Status information of a PowerHA agent job.
type PhaAgentJobStatusResponse struct {
	// Number of bytes downloaded so far.
	BytesDownloaded *int64 `json:"bytes_downloaded,omitempty"`

	// Timestamp when the job was created.
	CreationAt *strfmt.DateTime `json:"creation_at,omitempty"`

	// Name of the file that has been downloaded.
	FileName *string `json:"file_name,omitempty"`

	// Unique identifier of the job.
	JobID *string `json:"job_id,omitempty"`

	// Timestamp of the last update for this status.
	LastUpdatedAt *strfmt.DateTime `json:"last_updated_at,omitempty"`

	// Identifier of the service instance associated with the deployment.
	ServiceInstanceID *string `json:"service_instance_id,omitempty"`

	// Current status of the deployment.
	Status *string `json:"status,omitempty"`

	// Total size in bytes of the file that has to be downloaded.
	TotalBytes *int64 `json:"total_bytes,omitempty"`

	// Identifier of the virtual machine involved in the deployment.
	VMID *string `json:"vm_id,omitempty"`
}

// UnmarshalPhaAgentJobStatusResponse unmarshals an instance of PhaAgentJobStatusResponse from the specified map of raw messages.
func UnmarshalPhaAgentJobStatusResponse(m map[string]json.RawMessage, result interface{}) (err error) {
	obj := new(PhaAgentJobStatusResponse)
	err = core.UnmarshalPrimitive(m, "bytes_downloaded", &obj.BytesDownloaded)
	if err != nil {
		err = core.SDKErrorf(err, "", "bytes_downloaded-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "creation_at", &obj.CreationAt)
	if err != nil {
		err = core.SDKErrorf(err, "", "creation_at-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "file_name", &obj.FileName)
	if err != nil {
		err = core.SDKErrorf(err, "", "file_name-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "job_id", &obj.JobID)
	if err != nil {
		err = core.SDKErrorf(err, "", "job_id-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "last_updated_at", &obj.LastUpdatedAt)
	if err != nil {
		err = core.SDKErrorf(err, "", "last_updated_at-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "service_instance_id", &obj.ServiceInstanceID)
	if err != nil {
		err = core.SDKErrorf(err, "", "service_instance_id-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "status", &obj.Status)
	if err != nil {
		err = core.SDKErrorf(err, "", "status-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "total_bytes", &obj.TotalBytes)
	if err != nil {
		err = core.SDKErrorf(err, "", "total_bytes-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "vm_id", &obj.VMID)
	if err != nil {
		err = core.SDKErrorf(err, "", "vm_id-error", common.GetComponentInfo())
		return
	}
	reflect.ValueOf(result).Elem().Set(reflect.ValueOf(obj))
	return
}

// PhaDeploymentResponse : Details of a PowerHA deployment including cluster information, provisioning status, network configuration, and
// associated resources.
type PhaDeploymentResponse struct {
	// Cloud account identifier.
	CloudAccountID *string `json:"cloud_account_id,omitempty"`

	// Type of network connectivity.
	ConnectivityType *string `json:"connectivity_type,omitempty"`

	// Timestamp expressing creation time.
	CreationTime *string `json:"creation_time,omitempty"`

	// List of custom network CIDRs.
	CustomNetwork []string `json:"custom_network" validate:"required"`

	// Timestamp expressing deprovision time.
	DeprovisionTime *string `json:"deprovision_time,omitempty"`

	// Global unique identifier.
	GUID *string `json:"guid,omitempty"`

	// Indicates whether deployment is duplicate.
	IsDuplicate *bool `json:"is_duplicate,omitempty"`

	// Identifier for the service plan.
	PlanID *string `json:"plan_id,omitempty"`

	// Name of service plan.
	PlanName *string `json:"plan_name,omitempty"`

	// Name of the PowerHA cluster.
	PowerhaClusterName *string `json:"powerha_cluster_name,omitempty"`

	// Type of PowerHA cluster.
	PowerhaClusterType *string `json:"powerha_cluster_type,omitempty"`

	// PowerHA version level.
	PowerhaLevel *string `json:"powerha_level,omitempty"`

	// List of primary cluster nodes.
	PrimaryClusterNodesDetails []ClusterNodeInfo `json:"primary_cluster_nodes_details" validate:"required"`

	// Primary cluster location.
	PrimaryLocation *string `json:"primary_location,omitempty"`

	// name of the primary workspace region.
	PrimaryRegionName *string `json:"primary_region_name,omitempty"`

	// Primary workspace identifier.
	PrimaryWorkspace *string `json:"primary_workspace,omitempty"`

	// name of the primary workspace.
	PrimaryWorkspaceName *string `json:"primary_workspace_name,omitempty"`

	// Time stamp provisioning completed.
	ProvisionEndTime *string `json:"provision_end_time,omitempty"`

	// Provision request identifier.
	ID *string `json:"id,omitempty"`

	// Time stamp provisioning started.
	ProvisionStartTime *string `json:"provision_start_time,omitempty"`

	// Current provision status.
	ProvisionStatus *string `json:"provision_status,omitempty"`

	// Deployment region identifier.
	RegionID *string `json:"region_id,omitempty"`

	// Name of the resource group.
	ResourceGroup *string `json:"resource_group,omitempty"`

	// CRN of associated resource group.
	ResourceGroupCRN *string `json:"resource_group_crn,omitempty"`

	// Resource instance identifier.
	ResourceInstance *string `json:"resource_instance,omitempty"`

	// List of secondary cluster nodes.
	SecondaryClusterNodes []ClusterNodeInfo `json:"secondary_cluster_nodes" validate:"required"`

	// Secondary cluster location.
	SecondaryLocation *string `json:"secondary_location,omitempty"`

	// Secondary workspace identifier.
	SecondaryWorkspace *string `json:"secondary_workspace,omitempty"`

	// Description of provisioned service.
	ServiceDescription *string `json:"service_description,omitempty"`

	// Identifier for the service.
	ServiceID *string `json:"service_id,omitempty"`

	// Name of service.
	ServiceName *string `json:"service_name,omitempty"`

	// name of the standby workspace region.
	StandbyRegionName *string `json:"standby_region_name,omitempty"`

	// name of the standby workspace.
	StandbyWorkspaceName *string `json:"standby_workspace_name,omitempty"`

	// User defined tags.
	UserTags *string `json:"user_tags,omitempty"`
}

// UnmarshalPhaDeploymentResponse unmarshals an instance of PhaDeploymentResponse from the specified map of raw messages.
func UnmarshalPhaDeploymentResponse(m map[string]json.RawMessage, result interface{}) (err error) {
	obj := new(PhaDeploymentResponse)
	err = core.UnmarshalPrimitive(m, "cloud_account_id", &obj.CloudAccountID)
	if err != nil {
		err = core.SDKErrorf(err, "", "cloud_account_id-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "connectivity_type", &obj.ConnectivityType)
	if err != nil {
		err = core.SDKErrorf(err, "", "connectivity_type-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "creation_time", &obj.CreationTime)
	if err != nil {
		err = core.SDKErrorf(err, "", "creation_time-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "custom_network", &obj.CustomNetwork)
	if err != nil {
		err = core.SDKErrorf(err, "", "custom_network-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "deprovision_time", &obj.DeprovisionTime)
	if err != nil {
		err = core.SDKErrorf(err, "", "deprovision_time-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "guid", &obj.GUID)
	if err != nil {
		err = core.SDKErrorf(err, "", "guid-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "is_duplicate", &obj.IsDuplicate)
	if err != nil {
		err = core.SDKErrorf(err, "", "is_duplicate-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "plan_id", &obj.PlanID)
	if err != nil {
		err = core.SDKErrorf(err, "", "plan_id-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "plan_name", &obj.PlanName)
	if err != nil {
		err = core.SDKErrorf(err, "", "plan_name-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "powerha_cluster_name", &obj.PowerhaClusterName)
	if err != nil {
		err = core.SDKErrorf(err, "", "powerha_cluster_name-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "powerha_cluster_type", &obj.PowerhaClusterType)
	if err != nil {
		err = core.SDKErrorf(err, "", "powerha_cluster_type-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "powerha_level", &obj.PowerhaLevel)
	if err != nil {
		err = core.SDKErrorf(err, "", "powerha_level-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalModel(m, "primary_cluster_nodes_details", &obj.PrimaryClusterNodesDetails, UnmarshalClusterNodeInfo)
	if err != nil {
		err = core.SDKErrorf(err, "", "primary_cluster_nodes_details-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "primary_location", &obj.PrimaryLocation)
	if err != nil {
		err = core.SDKErrorf(err, "", "primary_location-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "primary_region_name", &obj.PrimaryRegionName)
	if err != nil {
		err = core.SDKErrorf(err, "", "primary_region_name-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "primary_workspace", &obj.PrimaryWorkspace)
	if err != nil {
		err = core.SDKErrorf(err, "", "primary_workspace-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "primary_workspace_name", &obj.PrimaryWorkspaceName)
	if err != nil {
		err = core.SDKErrorf(err, "", "primary_workspace_name-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "provision_end_time", &obj.ProvisionEndTime)
	if err != nil {
		err = core.SDKErrorf(err, "", "provision_end_time-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "id", &obj.ID)
	if err != nil {
		err = core.SDKErrorf(err, "", "id-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "provision_start_time", &obj.ProvisionStartTime)
	if err != nil {
		err = core.SDKErrorf(err, "", "provision_start_time-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "provision_status", &obj.ProvisionStatus)
	if err != nil {
		err = core.SDKErrorf(err, "", "provision_status-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "region_id", &obj.RegionID)
	if err != nil {
		err = core.SDKErrorf(err, "", "region_id-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "resource_group", &obj.ResourceGroup)
	if err != nil {
		err = core.SDKErrorf(err, "", "resource_group-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "resource_group_crn", &obj.ResourceGroupCRN)
	if err != nil {
		err = core.SDKErrorf(err, "", "resource_group_crn-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "resource_instance", &obj.ResourceInstance)
	if err != nil {
		err = core.SDKErrorf(err, "", "resource_instance-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalModel(m, "secondary_cluster_nodes", &obj.SecondaryClusterNodes, UnmarshalClusterNodeInfo)
	if err != nil {
		err = core.SDKErrorf(err, "", "secondary_cluster_nodes-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "secondary_location", &obj.SecondaryLocation)
	if err != nil {
		err = core.SDKErrorf(err, "", "secondary_location-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "secondary_workspace", &obj.SecondaryWorkspace)
	if err != nil {
		err = core.SDKErrorf(err, "", "secondary_workspace-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "service_description", &obj.ServiceDescription)
	if err != nil {
		err = core.SDKErrorf(err, "", "service_description-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "service_id", &obj.ServiceID)
	if err != nil {
		err = core.SDKErrorf(err, "", "service_id-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "service_name", &obj.ServiceName)
	if err != nil {
		err = core.SDKErrorf(err, "", "service_name-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "standby_region_name", &obj.StandbyRegionName)
	if err != nil {
		err = core.SDKErrorf(err, "", "standby_region_name-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "standby_workspace_name", &obj.StandbyWorkspaceName)
	if err != nil {
		err = core.SDKErrorf(err, "", "standby_workspace_name-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "user_tags", &obj.UserTags)
	if err != nil {
		err = core.SDKErrorf(err, "", "user_tags-error", common.GetComponentInfo())
		return
	}
	reflect.ValueOf(result).Elem().Set(reflect.ValueOf(obj))
	return
}

// PhaLocation : Details of a PowerHA supported location.
type PhaLocation struct {
	// Unique identifier for the location.
	ID *string `json:"id,omitempty"`

	// Human-readable name of the location.
	Name *string `json:"name,omitempty"`
}

// UnmarshalPhaLocation unmarshals an instance of PhaLocation from the specified map of raw messages.
func UnmarshalPhaLocation(m map[string]json.RawMessage, result interface{}) (err error) {
	obj := new(PhaLocation)
	err = core.UnmarshalPrimitive(m, "id", &obj.ID)
	if err != nil {
		err = core.SDKErrorf(err, "", "id-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "name", &obj.Name)
	if err != nil {
		err = core.SDKErrorf(err, "", "name-error", common.GetComponentInfo())
		return
	}
	reflect.ValueOf(result).Elem().Set(reflect.ValueOf(obj))
	return
}

// PhaSupportedLocationsResponse : List of PowerVS locations where PowerHA service is supported.
type PhaSupportedLocationsResponse struct {
	// Array of PowerVS locations where PowerHA service is supported.
	Locations []PhaLocation `json:"locations" validate:"required"`
}

// UnmarshalPhaSupportedLocationsResponse unmarshals an instance of PhaSupportedLocationsResponse from the specified map of raw messages.
func UnmarshalPhaSupportedLocationsResponse(m map[string]json.RawMessage, result interface{}) (err error) {
	obj := new(PhaSupportedLocationsResponse)
	err = core.UnmarshalModel(m, "locations", &obj.Locations, UnmarshalPhaLocation)
	if err != nil {
		err = core.SDKErrorf(err, "", "locations-error", common.GetComponentInfo())
		return
	}
	reflect.ValueOf(result).Elem().Set(reflect.ValueOf(obj))
	return
}

// PhaWorkspaceSummary : Summary information for a PowerHA workspace.
type PhaWorkspaceSummary struct {
	// Unique identifier of the workspace.
	ID *string `json:"id,omitempty"`

	// Name of the workspace.
	Name *string `json:"name,omitempty"`
}

// UnmarshalPhaWorkspaceSummary unmarshals an instance of PhaWorkspaceSummary from the specified map of raw messages.
func UnmarshalPhaWorkspaceSummary(m map[string]json.RawMessage, result interface{}) (err error) {
	obj := new(PhaWorkspaceSummary)
	err = core.UnmarshalPrimitive(m, "id", &obj.ID)
	if err != nil {
		err = core.SDKErrorf(err, "", "id-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "name", &obj.Name)
	if err != nil {
		err = core.SDKErrorf(err, "", "name-error", common.GetComponentInfo())
		return
	}
	reflect.ValueOf(result).Elem().Set(reflect.ValueOf(obj))
	return
}

// PhaWorkspacesRegionResponse : Response containing the list of workspaces for a specific region.
type PhaWorkspacesRegionResponse struct {
	// Array of workspace summaries within the region.
	Workspaces []PhaWorkspaceSummary `json:"workspaces" validate:"required"`
}

// UnmarshalPhaWorkspacesRegionResponse unmarshals an instance of PhaWorkspacesRegionResponse from the specified map of raw messages.
func UnmarshalPhaWorkspacesRegionResponse(m map[string]json.RawMessage, result interface{}) (err error) {
	obj := new(PhaWorkspacesRegionResponse)
	err = core.UnmarshalModel(m, "workspaces", &obj.Workspaces, UnmarshalPhaWorkspaceSummary)
	if err != nil {
		err = core.SDKErrorf(err, "", "workspaces-error", common.GetComponentInfo())
		return
	}
	reflect.ValueOf(result).Elem().Set(reflect.ValueOf(obj))
	return
}

// ServiceInstancePhaStatus : Current status information for a PHA service instance.
type ServiceInstancePhaStatus struct {
	// Name of the deployment associated with the service instance.
	DeploymentName *string `json:"deployment_name" validate:"required"`

	// Unique identifier for the provisioning operation.
	ProvisionID *string `json:"provision_id" validate:"required"`

	// Resource Group.
	ResourceGroup *string `json:"resource_group" validate:"required"`

	// Current operational status of the service instance.
	Status *string `json:"status" validate:"required"`
}

// UnmarshalServiceInstancePhaStatus unmarshals an instance of ServiceInstancePhaStatus from the specified map of raw messages.
func UnmarshalServiceInstancePhaStatus(m map[string]json.RawMessage, result interface{}) (err error) {
	obj := new(ServiceInstancePhaStatus)
	err = core.UnmarshalPrimitive(m, "deployment_name", &obj.DeploymentName)
	if err != nil {
		err = core.SDKErrorf(err, "", "deployment_name-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "provision_id", &obj.ProvisionID)
	if err != nil {
		err = core.SDKErrorf(err, "", "provision_id-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "resource_group", &obj.ResourceGroup)
	if err != nil {
		err = core.SDKErrorf(err, "", "resource_group-error", common.GetComponentInfo())
		return
	}
	err = core.UnmarshalPrimitive(m, "status", &obj.Status)
	if err != nil {
		err = core.SDKErrorf(err, "", "status-error", common.GetComponentInfo())
		return
	}
	reflect.ValueOf(result).Elem().Set(reflect.ValueOf(obj))
	return
}
